// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/config"
)

type BaselineWriter struct {
	SetBaselineStub        func(context.Context, string, string) error
	setBaselineMutex       sync.RWMutex
	setBaselineArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	setBaselineReturns struct {
		result1 error
	}
	setBaselineReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *BaselineWriter) SetBaseline(arg1 context.Context, arg2 string, arg3 string) error {
	fake.setBaselineMutex.Lock()
	ret, specificReturn := fake.setBaselineReturnsOnCall[len(fake.setBaselineArgsForCall)]
	fake.setBaselineArgsForCall = append(fake.setBaselineArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SetBaselineStub
	fakeReturns := fake.setBaselineReturns
	fake.recordInvocation("SetBaseline", []interface{}{arg1, arg2, arg3})
	fake.setBaselineMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *BaselineWriter) SetBaselineCallCount() int {
	fake.setBaselineMutex.RLock()
	defer fake.setBaselineMutex.RUnlock()
	return len(fake.setBaselineArgsForCall)
}

func (fake *BaselineWriter) SetBaselineCalls(stub func(context.Context, string, string) error) {
	fake.setBaselineMutex.Lock()
	defer fake.setBaselineMutex.Unlock()
	fake.SetBaselineStub = stub
}

func (fake *BaselineWriter) SetBaselineArgsForCall(i int) (context.Context, string, string) {
	fake.setBaselineMutex.RLock()
	defer fake.setBaselineMutex.RUnlock()
	argsForCall := fake.setBaselineArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *BaselineWriter) SetBaselineReturns(result1 error) {
	fake.setBaselineMutex.Lock()
	defer fake.setBaselineMutex.Unlock()
	fake.SetBaselineStub = nil
	fake.setBaselineReturns = struct {
		result1 error
	}{result1}
}

func (fake *BaselineWriter) SetBaselineReturnsOnCall(i int, result1 error) {
	fake.setBaselineMutex.Lock()
	defer fake.setBaselineMutex.Unlock()
	fake.SetBaselineStub = nil
	if fake.setBaselineReturnsOnCall == nil {
		fake.setBaselineReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setBaselineReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *BaselineWriter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *BaselineWriter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ config.BaselineWriter = new(BaselineWriter)
