// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/vault-cli/pkg/ops"
)

type ClaudeResumer struct {
	ResumeSessionStub        func(string, string) error
	resumeSessionMutex       sync.RWMutex
	resumeSessionArgsForCall []struct {
		arg1 string
		arg2 string
	}
	resumeSessionReturns struct {
		result1 error
	}
	resumeSessionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ClaudeResumer) ResumeSession(arg1 string, arg2 string) error {
	fake.resumeSessionMutex.Lock()
	ret, specificReturn := fake.resumeSessionReturnsOnCall[len(fake.resumeSessionArgsForCall)]
	fake.resumeSessionArgsForCall = append(fake.resumeSessionArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.ResumeSessionStub
	fakeReturns := fake.resumeSessionReturns
	fake.recordInvocation("ResumeSession", []interface{}{arg1, arg2})
	fake.resumeSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ClaudeResumer) ResumeSessionCallCount() int {
	fake.resumeSessionMutex.RLock()
	defer fake.resumeSessionMutex.RUnlock()
	return len(fake.resumeSessionArgsForCall)
}

func (fake *ClaudeResumer) ResumeSessionCalls(stub func(string, string) error) {
	fake.resumeSessionMutex.Lock()
	defer fake.resumeSessionMutex.Unlock()
	fake.ResumeSessionStub = stub
}

func (fake *ClaudeResumer) ResumeSessionArgsForCall(i int) (string, string) {
	fake.resumeSessionMutex.RLock()
	defer fake.resumeSessionMutex.RUnlock()
	argsForCall := fake.resumeSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ClaudeResumer) ResumeSessionReturns(result1 error) {
	fake.resumeSessionMutex.Lock()
	defer fake.resumeSessionMutex.Unlock()
	fake.ResumeSessionStub = nil
	fake.resumeSessionReturns = struct {
		result1 error
	}{result1}
}

func (fake *ClaudeResumer) ResumeSessionReturnsOnCall(i int, result1 error) {
	fake.resumeSessionMutex.Lock()
	defer fake.resumeSessionMutex.Unlock()
	fake.ResumeSessionStub = nil
	if fake.resumeSessionReturnsOnCall == nil {
		fake.resumeSessionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resumeSessionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ClaudeResumer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ClaudeResumer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ops.ClaudeResumer = new(ClaudeResumer)
