// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/ops"
)

type ClaudeSessionStarter struct {
	StartSessionStub        func(context.Context, string, string, string, string, bool) error
	startSessionMutex       sync.RWMutex
	startSessionArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 bool
	}
	startSessionReturns struct {
		result1 error
	}
	startSessionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ClaudeSessionStarter) StartSession(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string, arg6 bool) error {
	fake.startSessionMutex.Lock()
	ret, specificReturn := fake.startSessionReturnsOnCall[len(fake.startSessionArgsForCall)]
	fake.startSessionArgsForCall = append(fake.startSessionArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
		arg6 bool
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.StartSessionStub
	fakeReturns := fake.startSessionReturns
	fake.recordInvocation("StartSession", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.startSessionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ClaudeSessionStarter) StartSessionCallCount() int {
	fake.startSessionMutex.RLock()
	defer fake.startSessionMutex.RUnlock()
	return len(fake.startSessionArgsForCall)
}

func (fake *ClaudeSessionStarter) StartSessionCalls(stub func(context.Context, string, string, string, string, bool) error) {
	fake.startSessionMutex.Lock()
	defer fake.startSessionMutex.Unlock()
	fake.StartSessionStub = stub
}

func (fake *ClaudeSessionStarter) StartSessionArgsForCall(i int) (context.Context, string, string, string, string, bool) {
	fake.startSessionMutex.RLock()
	defer fake.startSessionMutex.RUnlock()
	argsForCall := fake.startSessionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *ClaudeSessionStarter) StartSessionReturns(result1 error) {
	fake.startSessionMutex.Lock()
	defer fake.startSessionMutex.Unlock()
	fake.StartSessionStub = nil
	fake.startSessionReturns = struct {
		result1 error
	}{result1}
}

func (fake *ClaudeSessionStarter) StartSessionReturnsOnCall(i int, result1 error) {
	fake.startSessionMutex.Lock()
	defer fake.startSessionMutex.Unlock()
	fake.StartSessionStub = nil
	if fake.startSessionReturnsOnCall == nil {
		fake.startSessionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.startSessionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ClaudeSessionStarter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ClaudeSessionStarter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ops.ClaudeSessionStarter = new(ClaudeSessionStarter)
