// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/config"
)

type Loader struct {
	GetVaultStub        func(context.Context, string) (*config.Vault, error)
	getVaultMutex       sync.RWMutex
	getVaultArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getVaultReturns struct {
		result1 *config.Vault
		result2 error
	}
	getVaultReturnsOnCall map[int]struct {
		result1 *config.Vault
		result2 error
	}
	GetVaultPathStub        func(context.Context, string) (string, error)
	getVaultPathMutex       sync.RWMutex
	getVaultPathArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getVaultPathReturns struct {
		result1 string
		result2 error
	}
	getVaultPathReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	LoadStub        func(context.Context) (*config.Config, error)
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 context.Context
	}
	loadReturns struct {
		result1 *config.Config
		result2 error
	}
	loadReturnsOnCall map[int]struct {
		result1 *config.Config
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Loader) GetVault(arg1 context.Context, arg2 string) (*config.Vault, error) {
	fake.getVaultMutex.Lock()
	ret, specificReturn := fake.getVaultReturnsOnCall[len(fake.getVaultArgsForCall)]
	fake.getVaultArgsForCall = append(fake.getVaultArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetVaultStub
	fakeReturns := fake.getVaultReturns
	fake.recordInvocation("GetVault", []interface{}{arg1, arg2})
	fake.getVaultMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Loader) GetVaultCallCount() int {
	fake.getVaultMutex.RLock()
	defer fake.getVaultMutex.RUnlock()
	return len(fake.getVaultArgsForCall)
}

func (fake *Loader) GetVaultCalls(stub func(context.Context, string) (*config.Vault, error)) {
	fake.getVaultMutex.Lock()
	defer fake.getVaultMutex.Unlock()
	fake.GetVaultStub = stub
}

func (fake *Loader) GetVaultArgsForCall(i int) (context.Context, string) {
	fake.getVaultMutex.RLock()
	defer fake.getVaultMutex.RUnlock()
	argsForCall := fake.getVaultArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Loader) GetVaultReturns(result1 *config.Vault, result2 error) {
	fake.getVaultMutex.Lock()
	defer fake.getVaultMutex.Unlock()
	fake.GetVaultStub = nil
	fake.getVaultReturns = struct {
		result1 *config.Vault
		result2 error
	}{result1, result2}
}

func (fake *Loader) GetVaultReturnsOnCall(i int, result1 *config.Vault, result2 error) {
	fake.getVaultMutex.Lock()
	defer fake.getVaultMutex.Unlock()
	fake.GetVaultStub = nil
	if fake.getVaultReturnsOnCall == nil {
		fake.getVaultReturnsOnCall = make(map[int]struct {
			result1 *config.Vault
			result2 error
		})
	}
	fake.getVaultReturnsOnCall[i] = struct {
		result1 *config.Vault
		result2 error
	}{result1, result2}
}

func (fake *Loader) GetVaultPath(arg1 context.Context, arg2 string) (string, error) {
	fake.getVaultPathMutex.Lock()
	ret, specificReturn := fake.getVaultPathReturnsOnCall[len(fake.getVaultPathArgsForCall)]
	fake.getVaultPathArgsForCall = append(fake.getVaultPathArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetVaultPathStub
	fakeReturns := fake.getVaultPathReturns
	fake.recordInvocation("GetVaultPath", []interface{}{arg1, arg2})
	fake.getVaultPathMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Loader) GetVaultPathCallCount() int {
	fake.getVaultPathMutex.RLock()
	defer fake.getVaultPathMutex.RUnlock()
	return len(fake.getVaultPathArgsForCall)
}

func (fake *Loader) GetVaultPathCalls(stub func(context.Context, string) (string, error)) {
	fake.getVaultPathMutex.Lock()
	defer fake.getVaultPathMutex.Unlock()
	fake.GetVaultPathStub = stub
}

func (fake *Loader) GetVaultPathArgsForCall(i int) (context.Context, string) {
	fake.getVaultPathMutex.RLock()
	defer fake.getVaultPathMutex.RUnlock()
	argsForCall := fake.getVaultPathArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Loader) GetVaultPathReturns(result1 string, result2 error) {
	fake.getVaultPathMutex.Lock()
	defer fake.getVaultPathMutex.Unlock()
	fake.GetVaultPathStub = nil
	fake.getVaultPathReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Loader) GetVaultPathReturnsOnCall(i int, result1 string, result2 error) {
	fake.getVaultPathMutex.Lock()
	defer fake.getVaultPathMutex.Unlock()
	fake.GetVaultPathStub = nil
	if fake.getVaultPathReturnsOnCall == nil {
		fake.getVaultPathReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getVaultPathReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Loader) Load(arg1 context.Context) (*config.Config, error) {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Loader) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *Loader) LoadCalls(stub func(context.Context) (*config.Config, error)) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *Loader) LoadArgsForCall(i int) context.Context {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Loader) LoadReturns(result1 *config.Config, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 *config.Config
		result2 error
	}{result1, result2}
}

func (fake *Loader) LoadReturnsOnCall(i int, result1 *config.Config, result2 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 *config.Config
			result2 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 *config.Config
		result2 error
	}{result1, result2}
}

func (fake *Loader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Loader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ config.Loader = new(Loader)
