// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/storage"
)

type DailyNoteStorage struct {
	ReadDailyNoteStub        func(context.Context, string, string) (string, error)
	readDailyNoteMutex       sync.RWMutex
	readDailyNoteArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	readDailyNoteReturns struct {
		result1 string
		result2 error
	}
	readDailyNoteReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	WriteDailyNoteStub        func(context.Context, string, string, string) error
	writeDailyNoteMutex       sync.RWMutex
	writeDailyNoteArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	writeDailyNoteReturns struct {
		result1 error
	}
	writeDailyNoteReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DailyNoteStorage) ReadDailyNote(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.readDailyNoteMutex.Lock()
	ret, specificReturn := fake.readDailyNoteReturnsOnCall[len(fake.readDailyNoteArgsForCall)]
	fake.readDailyNoteArgsForCall = append(fake.readDailyNoteArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ReadDailyNoteStub
	fakeReturns := fake.readDailyNoteReturns
	fake.recordInvocation("ReadDailyNote", []interface{}{arg1, arg2, arg3})
	fake.readDailyNoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *DailyNoteStorage) ReadDailyNoteCallCount() int {
	fake.readDailyNoteMutex.RLock()
	defer fake.readDailyNoteMutex.RUnlock()
	return len(fake.readDailyNoteArgsForCall)
}

func (fake *DailyNoteStorage) ReadDailyNoteCalls(stub func(context.Context, string, string) (string, error)) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = stub
}

func (fake *DailyNoteStorage) ReadDailyNoteArgsForCall(i int) (context.Context, string, string) {
	fake.readDailyNoteMutex.RLock()
	defer fake.readDailyNoteMutex.RUnlock()
	argsForCall := fake.readDailyNoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *DailyNoteStorage) ReadDailyNoteReturns(result1 string, result2 error) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = nil
	fake.readDailyNoteReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *DailyNoteStorage) ReadDailyNoteReturnsOnCall(i int, result1 string, result2 error) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = nil
	if fake.readDailyNoteReturnsOnCall == nil {
		fake.readDailyNoteReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.readDailyNoteReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *DailyNoteStorage) WriteDailyNote(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.writeDailyNoteMutex.Lock()
	ret, specificReturn := fake.writeDailyNoteReturnsOnCall[len(fake.writeDailyNoteArgsForCall)]
	fake.writeDailyNoteArgsForCall = append(fake.writeDailyNoteArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.WriteDailyNoteStub
	fakeReturns := fake.writeDailyNoteReturns
	fake.recordInvocation("WriteDailyNote", []interface{}{arg1, arg2, arg3, arg4})
	fake.writeDailyNoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *DailyNoteStorage) WriteDailyNoteCallCount() int {
	fake.writeDailyNoteMutex.RLock()
	defer fake.writeDailyNoteMutex.RUnlock()
	return len(fake.writeDailyNoteArgsForCall)
}

func (fake *DailyNoteStorage) WriteDailyNoteCalls(stub func(context.Context, string, string, string) error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = stub
}

func (fake *DailyNoteStorage) WriteDailyNoteArgsForCall(i int) (context.Context, string, string, string) {
	fake.writeDailyNoteMutex.RLock()
	defer fake.writeDailyNoteMutex.RUnlock()
	argsForCall := fake.writeDailyNoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *DailyNoteStorage) WriteDailyNoteReturns(result1 error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = nil
	fake.writeDailyNoteReturns = struct {
		result1 error
	}{result1}
}

func (fake *DailyNoteStorage) WriteDailyNoteReturnsOnCall(i int, result1 error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = nil
	if fake.writeDailyNoteReturnsOnCall == nil {
		fake.writeDailyNoteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeDailyNoteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *DailyNoteStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DailyNoteStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.DailyNoteStorage = new(DailyNoteStorage)
