// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-cli/pkg/storage"
)

type GoalStorage struct {
	FindGoalByNameStub        func(context.Context, string, string) (*domain.Goal, error)
	findGoalByNameMutex       sync.RWMutex
	findGoalByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findGoalByNameReturns struct {
		result1 *domain.Goal
		result2 error
	}
	findGoalByNameReturnsOnCall map[int]struct {
		result1 *domain.Goal
		result2 error
	}
	WriteGoalStub        func(context.Context, *domain.Goal) error
	writeGoalMutex       sync.RWMutex
	writeGoalArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Goal
	}
	writeGoalReturns struct {
		result1 error
	}
	writeGoalReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GoalStorage) FindGoalByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Goal, error) {
	fake.findGoalByNameMutex.Lock()
	ret, specificReturn := fake.findGoalByNameReturnsOnCall[len(fake.findGoalByNameArgsForCall)]
	fake.findGoalByNameArgsForCall = append(fake.findGoalByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindGoalByNameStub
	fakeReturns := fake.findGoalByNameReturns
	fake.recordInvocation("FindGoalByName", []interface{}{arg1, arg2, arg3})
	fake.findGoalByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GoalStorage) FindGoalByNameCallCount() int {
	fake.findGoalByNameMutex.RLock()
	defer fake.findGoalByNameMutex.RUnlock()
	return len(fake.findGoalByNameArgsForCall)
}

func (fake *GoalStorage) FindGoalByNameCalls(stub func(context.Context, string, string) (*domain.Goal, error)) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = stub
}

func (fake *GoalStorage) FindGoalByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findGoalByNameMutex.RLock()
	defer fake.findGoalByNameMutex.RUnlock()
	argsForCall := fake.findGoalByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GoalStorage) FindGoalByNameReturns(result1 *domain.Goal, result2 error) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = nil
	fake.findGoalByNameReturns = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *GoalStorage) FindGoalByNameReturnsOnCall(i int, result1 *domain.Goal, result2 error) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = nil
	if fake.findGoalByNameReturnsOnCall == nil {
		fake.findGoalByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Goal
			result2 error
		})
	}
	fake.findGoalByNameReturnsOnCall[i] = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *GoalStorage) WriteGoal(arg1 context.Context, arg2 *domain.Goal) error {
	fake.writeGoalMutex.Lock()
	ret, specificReturn := fake.writeGoalReturnsOnCall[len(fake.writeGoalArgsForCall)]
	fake.writeGoalArgsForCall = append(fake.writeGoalArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Goal
	}{arg1, arg2})
	stub := fake.WriteGoalStub
	fakeReturns := fake.writeGoalReturns
	fake.recordInvocation("WriteGoal", []interface{}{arg1, arg2})
	fake.writeGoalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GoalStorage) WriteGoalCallCount() int {
	fake.writeGoalMutex.RLock()
	defer fake.writeGoalMutex.RUnlock()
	return len(fake.writeGoalArgsForCall)
}

func (fake *GoalStorage) WriteGoalCalls(stub func(context.Context, *domain.Goal) error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = stub
}

func (fake *GoalStorage) WriteGoalArgsForCall(i int) (context.Context, *domain.Goal) {
	fake.writeGoalMutex.RLock()
	defer fake.writeGoalMutex.RUnlock()
	argsForCall := fake.writeGoalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GoalStorage) WriteGoalReturns(result1 error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = nil
	fake.writeGoalReturns = struct {
		result1 error
	}{result1}
}

func (fake *GoalStorage) WriteGoalReturnsOnCall(i int, result1 error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = nil
	if fake.writeGoalReturnsOnCall == nil {
		fake.writeGoalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeGoalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GoalStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GoalStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.GoalStorage = new(GoalStorage)
