// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/notification/command/notification"
	"github.com/bborbe/vault-cli/pkg/ops"
)

type NotificationPublishCommandSender struct {
	SendPublishNotificationCommandStub        func(context.Context, notification.NotificationPublishCommand) error
	sendPublishNotificationCommandMutex       sync.RWMutex
	sendPublishNotificationCommandArgsForCall []struct {
		arg1 context.Context
		arg2 notification.NotificationPublishCommand
	}
	sendPublishNotificationCommandReturns struct {
		result1 error
	}
	sendPublishNotificationCommandReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NotificationPublishCommandSender) SendPublishNotificationCommand(arg1 context.Context, arg2 notification.NotificationPublishCommand) error {
	fake.sendPublishNotificationCommandMutex.Lock()
	ret, specificReturn := fake.sendPublishNotificationCommandReturnsOnCall[len(fake.sendPublishNotificationCommandArgsForCall)]
	fake.sendPublishNotificationCommandArgsForCall = append(fake.sendPublishNotificationCommandArgsForCall, struct {
		arg1 context.Context
		arg2 notification.NotificationPublishCommand
	}{arg1, arg2})
	stub := fake.SendPublishNotificationCommandStub
	fakeReturns := fake.sendPublishNotificationCommandReturns
	fake.recordInvocation("SendPublishNotificationCommand", []interface{}{arg1, arg2})
	fake.sendPublishNotificationCommandMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *NotificationPublishCommandSender) SendPublishNotificationCommandCallCount() int {
	fake.sendPublishNotificationCommandMutex.RLock()
	defer fake.sendPublishNotificationCommandMutex.RUnlock()
	return len(fake.sendPublishNotificationCommandArgsForCall)
}

func (fake *NotificationPublishCommandSender) SendPublishNotificationCommandCalls(stub func(context.Context, notification.NotificationPublishCommand) error) {
	fake.sendPublishNotificationCommandMutex.Lock()
	defer fake.sendPublishNotificationCommandMutex.Unlock()
	fake.SendPublishNotificationCommandStub = stub
}

func (fake *NotificationPublishCommandSender) SendPublishNotificationCommandArgsForCall(i int) (context.Context, notification.NotificationPublishCommand) {
	fake.sendPublishNotificationCommandMutex.RLock()
	defer fake.sendPublishNotificationCommandMutex.RUnlock()
	argsForCall := fake.sendPublishNotificationCommandArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *NotificationPublishCommandSender) SendPublishNotificationCommandReturns(result1 error) {
	fake.sendPublishNotificationCommandMutex.Lock()
	defer fake.sendPublishNotificationCommandMutex.Unlock()
	fake.SendPublishNotificationCommandStub = nil
	fake.sendPublishNotificationCommandReturns = struct {
		result1 error
	}{result1}
}

func (fake *NotificationPublishCommandSender) SendPublishNotificationCommandReturnsOnCall(i int, result1 error) {
	fake.sendPublishNotificationCommandMutex.Lock()
	defer fake.sendPublishNotificationCommandMutex.Unlock()
	fake.SendPublishNotificationCommandStub = nil
	if fake.sendPublishNotificationCommandReturnsOnCall == nil {
		fake.sendPublishNotificationCommandReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendPublishNotificationCommandReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *NotificationPublishCommandSender) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NotificationPublishCommandSender) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ops.NotificationPublishCommandSender = new(NotificationPublishCommandSender)
