// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-cli/pkg/storage"
)

type ObjectiveStorage struct {
	FindObjectiveByNameStub        func(context.Context, string, string) (*domain.Objective, error)
	findObjectiveByNameMutex       sync.RWMutex
	findObjectiveByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findObjectiveByNameReturns struct {
		result1 *domain.Objective
		result2 error
	}
	findObjectiveByNameReturnsOnCall map[int]struct {
		result1 *domain.Objective
		result2 error
	}
	WriteObjectiveStub        func(context.Context, *domain.Objective) error
	writeObjectiveMutex       sync.RWMutex
	writeObjectiveArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Objective
	}
	writeObjectiveReturns struct {
		result1 error
	}
	writeObjectiveReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ObjectiveStorage) FindObjectiveByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Objective, error) {
	fake.findObjectiveByNameMutex.Lock()
	ret, specificReturn := fake.findObjectiveByNameReturnsOnCall[len(fake.findObjectiveByNameArgsForCall)]
	fake.findObjectiveByNameArgsForCall = append(fake.findObjectiveByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindObjectiveByNameStub
	fakeReturns := fake.findObjectiveByNameReturns
	fake.recordInvocation("FindObjectiveByName", []interface{}{arg1, arg2, arg3})
	fake.findObjectiveByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ObjectiveStorage) FindObjectiveByNameCallCount() int {
	fake.findObjectiveByNameMutex.RLock()
	defer fake.findObjectiveByNameMutex.RUnlock()
	return len(fake.findObjectiveByNameArgsForCall)
}

func (fake *ObjectiveStorage) FindObjectiveByNameCalls(stub func(context.Context, string, string) (*domain.Objective, error)) {
	fake.findObjectiveByNameMutex.Lock()
	defer fake.findObjectiveByNameMutex.Unlock()
	fake.FindObjectiveByNameStub = stub
}

func (fake *ObjectiveStorage) FindObjectiveByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findObjectiveByNameMutex.RLock()
	defer fake.findObjectiveByNameMutex.RUnlock()
	argsForCall := fake.findObjectiveByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ObjectiveStorage) FindObjectiveByNameReturns(result1 *domain.Objective, result2 error) {
	fake.findObjectiveByNameMutex.Lock()
	defer fake.findObjectiveByNameMutex.Unlock()
	fake.FindObjectiveByNameStub = nil
	fake.findObjectiveByNameReturns = struct {
		result1 *domain.Objective
		result2 error
	}{result1, result2}
}

func (fake *ObjectiveStorage) FindObjectiveByNameReturnsOnCall(i int, result1 *domain.Objective, result2 error) {
	fake.findObjectiveByNameMutex.Lock()
	defer fake.findObjectiveByNameMutex.Unlock()
	fake.FindObjectiveByNameStub = nil
	if fake.findObjectiveByNameReturnsOnCall == nil {
		fake.findObjectiveByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Objective
			result2 error
		})
	}
	fake.findObjectiveByNameReturnsOnCall[i] = struct {
		result1 *domain.Objective
		result2 error
	}{result1, result2}
}

func (fake *ObjectiveStorage) WriteObjective(arg1 context.Context, arg2 *domain.Objective) error {
	fake.writeObjectiveMutex.Lock()
	ret, specificReturn := fake.writeObjectiveReturnsOnCall[len(fake.writeObjectiveArgsForCall)]
	fake.writeObjectiveArgsForCall = append(fake.writeObjectiveArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Objective
	}{arg1, arg2})
	stub := fake.WriteObjectiveStub
	fakeReturns := fake.writeObjectiveReturns
	fake.recordInvocation("WriteObjective", []interface{}{arg1, arg2})
	fake.writeObjectiveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ObjectiveStorage) WriteObjectiveCallCount() int {
	fake.writeObjectiveMutex.RLock()
	defer fake.writeObjectiveMutex.RUnlock()
	return len(fake.writeObjectiveArgsForCall)
}

func (fake *ObjectiveStorage) WriteObjectiveCalls(stub func(context.Context, *domain.Objective) error) {
	fake.writeObjectiveMutex.Lock()
	defer fake.writeObjectiveMutex.Unlock()
	fake.WriteObjectiveStub = stub
}

func (fake *ObjectiveStorage) WriteObjectiveArgsForCall(i int) (context.Context, *domain.Objective) {
	fake.writeObjectiveMutex.RLock()
	defer fake.writeObjectiveMutex.RUnlock()
	argsForCall := fake.writeObjectiveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ObjectiveStorage) WriteObjectiveReturns(result1 error) {
	fake.writeObjectiveMutex.Lock()
	defer fake.writeObjectiveMutex.Unlock()
	fake.WriteObjectiveStub = nil
	fake.writeObjectiveReturns = struct {
		result1 error
	}{result1}
}

func (fake *ObjectiveStorage) WriteObjectiveReturnsOnCall(i int, result1 error) {
	fake.writeObjectiveMutex.Lock()
	defer fake.writeObjectiveMutex.Unlock()
	fake.WriteObjectiveStub = nil
	if fake.writeObjectiveReturnsOnCall == nil {
		fake.writeObjectiveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeObjectiveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ObjectiveStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ObjectiveStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.ObjectiveStorage = new(ObjectiveStorage)
