// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-cli/pkg/storage"
)

type PageStorage struct {
	ListPagesStub        func(context.Context, string, string) ([]*domain.Task, error)
	listPagesMutex       sync.RWMutex
	listPagesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	listPagesReturns struct {
		result1 []*domain.Task
		result2 error
	}
	listPagesReturnsOnCall map[int]struct {
		result1 []*domain.Task
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PageStorage) ListPages(arg1 context.Context, arg2 string, arg3 string) ([]*domain.Task, error) {
	fake.listPagesMutex.Lock()
	ret, specificReturn := fake.listPagesReturnsOnCall[len(fake.listPagesArgsForCall)]
	fake.listPagesArgsForCall = append(fake.listPagesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ListPagesStub
	fakeReturns := fake.listPagesReturns
	fake.recordInvocation("ListPages", []interface{}{arg1, arg2, arg3})
	fake.listPagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PageStorage) ListPagesCallCount() int {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	return len(fake.listPagesArgsForCall)
}

func (fake *PageStorage) ListPagesCalls(stub func(context.Context, string, string) ([]*domain.Task, error)) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = stub
}

func (fake *PageStorage) ListPagesArgsForCall(i int) (context.Context, string, string) {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	argsForCall := fake.listPagesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *PageStorage) ListPagesReturns(result1 []*domain.Task, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	fake.listPagesReturns = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *PageStorage) ListPagesReturnsOnCall(i int, result1 []*domain.Task, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	if fake.listPagesReturnsOnCall == nil {
		fake.listPagesReturnsOnCall = make(map[int]struct {
			result1 []*domain.Task
			result2 error
		})
	}
	fake.listPagesReturnsOnCall[i] = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *PageStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PageStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.PageStorage = new(PageStorage)
