// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-cli/pkg/storage"
)

type Storage struct {
	FindDecisionByNameStub        func(context.Context, string, string) (*domain.Decision, error)
	findDecisionByNameMutex       sync.RWMutex
	findDecisionByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findDecisionByNameReturns struct {
		result1 *domain.Decision
		result2 error
	}
	findDecisionByNameReturnsOnCall map[int]struct {
		result1 *domain.Decision
		result2 error
	}
	FindGoalByNameStub        func(context.Context, string, string) (*domain.Goal, error)
	findGoalByNameMutex       sync.RWMutex
	findGoalByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findGoalByNameReturns struct {
		result1 *domain.Goal
		result2 error
	}
	findGoalByNameReturnsOnCall map[int]struct {
		result1 *domain.Goal
		result2 error
	}
	FindObjectiveByNameStub        func(context.Context, string, string) (*domain.Objective, error)
	findObjectiveByNameMutex       sync.RWMutex
	findObjectiveByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findObjectiveByNameReturns struct {
		result1 *domain.Objective
		result2 error
	}
	findObjectiveByNameReturnsOnCall map[int]struct {
		result1 *domain.Objective
		result2 error
	}
	FindTaskByNameStub        func(context.Context, string, string) (*domain.Task, error)
	findTaskByNameMutex       sync.RWMutex
	findTaskByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findTaskByNameReturns struct {
		result1 *domain.Task
		result2 error
	}
	findTaskByNameReturnsOnCall map[int]struct {
		result1 *domain.Task
		result2 error
	}
	FindThemeByNameStub        func(context.Context, string, string) (*domain.Theme, error)
	findThemeByNameMutex       sync.RWMutex
	findThemeByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findThemeByNameReturns struct {
		result1 *domain.Theme
		result2 error
	}
	findThemeByNameReturnsOnCall map[int]struct {
		result1 *domain.Theme
		result2 error
	}
	FindVisionByNameStub        func(context.Context, string, string) (*domain.Vision, error)
	findVisionByNameMutex       sync.RWMutex
	findVisionByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findVisionByNameReturns struct {
		result1 *domain.Vision
		result2 error
	}
	findVisionByNameReturnsOnCall map[int]struct {
		result1 *domain.Vision
		result2 error
	}
	ListDecisionsStub        func(context.Context, string) ([]*domain.Decision, error)
	listDecisionsMutex       sync.RWMutex
	listDecisionsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listDecisionsReturns struct {
		result1 []*domain.Decision
		result2 error
	}
	listDecisionsReturnsOnCall map[int]struct {
		result1 []*domain.Decision
		result2 error
	}
	ListPagesStub        func(context.Context, string, string) ([]*domain.Task, error)
	listPagesMutex       sync.RWMutex
	listPagesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	listPagesReturns struct {
		result1 []*domain.Task
		result2 error
	}
	listPagesReturnsOnCall map[int]struct {
		result1 []*domain.Task
		result2 error
	}
	ListTasksStub        func(context.Context, string) ([]*domain.Task, error)
	listTasksMutex       sync.RWMutex
	listTasksArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listTasksReturns struct {
		result1 []*domain.Task
		result2 error
	}
	listTasksReturnsOnCall map[int]struct {
		result1 []*domain.Task
		result2 error
	}
	ReadDailyNoteStub        func(context.Context, string, string) (string, error)
	readDailyNoteMutex       sync.RWMutex
	readDailyNoteArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	readDailyNoteReturns struct {
		result1 string
		result2 error
	}
	readDailyNoteReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ReadGoalStub        func(context.Context, string, domain.GoalID) (*domain.Goal, error)
	readGoalMutex       sync.RWMutex
	readGoalArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 domain.GoalID
	}
	readGoalReturns struct {
		result1 *domain.Goal
		result2 error
	}
	readGoalReturnsOnCall map[int]struct {
		result1 *domain.Goal
		result2 error
	}
	ReadObjectiveStub        func(context.Context, string, domain.ObjectiveID) (*domain.Objective, error)
	readObjectiveMutex       sync.RWMutex
	readObjectiveArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 domain.ObjectiveID
	}
	readObjectiveReturns struct {
		result1 *domain.Objective
		result2 error
	}
	readObjectiveReturnsOnCall map[int]struct {
		result1 *domain.Objective
		result2 error
	}
	ReadTaskStub        func(context.Context, string, domain.TaskID) (*domain.Task, error)
	readTaskMutex       sync.RWMutex
	readTaskArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 domain.TaskID
	}
	readTaskReturns struct {
		result1 *domain.Task
		result2 error
	}
	readTaskReturnsOnCall map[int]struct {
		result1 *domain.Task
		result2 error
	}
	ReadThemeStub        func(context.Context, string, domain.ThemeID) (*domain.Theme, error)
	readThemeMutex       sync.RWMutex
	readThemeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 domain.ThemeID
	}
	readThemeReturns struct {
		result1 *domain.Theme
		result2 error
	}
	readThemeReturnsOnCall map[int]struct {
		result1 *domain.Theme
		result2 error
	}
	ReadVisionStub        func(context.Context, string, domain.VisionID) (*domain.Vision, error)
	readVisionMutex       sync.RWMutex
	readVisionArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 domain.VisionID
	}
	readVisionReturns struct {
		result1 *domain.Vision
		result2 error
	}
	readVisionReturnsOnCall map[int]struct {
		result1 *domain.Vision
		result2 error
	}
	WriteDailyNoteStub        func(context.Context, string, string, string) error
	writeDailyNoteMutex       sync.RWMutex
	writeDailyNoteArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	writeDailyNoteReturns struct {
		result1 error
	}
	writeDailyNoteReturnsOnCall map[int]struct {
		result1 error
	}
	WriteDecisionStub        func(context.Context, *domain.Decision) error
	writeDecisionMutex       sync.RWMutex
	writeDecisionArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Decision
	}
	writeDecisionReturns struct {
		result1 error
	}
	writeDecisionReturnsOnCall map[int]struct {
		result1 error
	}
	WriteGoalStub        func(context.Context, *domain.Goal) error
	writeGoalMutex       sync.RWMutex
	writeGoalArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Goal
	}
	writeGoalReturns struct {
		result1 error
	}
	writeGoalReturnsOnCall map[int]struct {
		result1 error
	}
	WriteObjectiveStub        func(context.Context, *domain.Objective) error
	writeObjectiveMutex       sync.RWMutex
	writeObjectiveArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Objective
	}
	writeObjectiveReturns struct {
		result1 error
	}
	writeObjectiveReturnsOnCall map[int]struct {
		result1 error
	}
	WriteTaskStub        func(context.Context, *domain.Task) error
	writeTaskMutex       sync.RWMutex
	writeTaskArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Task
	}
	writeTaskReturns struct {
		result1 error
	}
	writeTaskReturnsOnCall map[int]struct {
		result1 error
	}
	WriteThemeStub        func(context.Context, *domain.Theme) error
	writeThemeMutex       sync.RWMutex
	writeThemeArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Theme
	}
	writeThemeReturns struct {
		result1 error
	}
	writeThemeReturnsOnCall map[int]struct {
		result1 error
	}
	WriteVisionStub        func(context.Context, *domain.Vision) error
	writeVisionMutex       sync.RWMutex
	writeVisionArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Vision
	}
	writeVisionReturns struct {
		result1 error
	}
	writeVisionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Storage) FindDecisionByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Decision, error) {
	fake.findDecisionByNameMutex.Lock()
	ret, specificReturn := fake.findDecisionByNameReturnsOnCall[len(fake.findDecisionByNameArgsForCall)]
	fake.findDecisionByNameArgsForCall = append(fake.findDecisionByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindDecisionByNameStub
	fakeReturns := fake.findDecisionByNameReturns
	fake.recordInvocation("FindDecisionByName", []interface{}{arg1, arg2, arg3})
	fake.findDecisionByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) FindDecisionByNameCallCount() int {
	fake.findDecisionByNameMutex.RLock()
	defer fake.findDecisionByNameMutex.RUnlock()
	return len(fake.findDecisionByNameArgsForCall)
}

func (fake *Storage) FindDecisionByNameCalls(stub func(context.Context, string, string) (*domain.Decision, error)) {
	fake.findDecisionByNameMutex.Lock()
	defer fake.findDecisionByNameMutex.Unlock()
	fake.FindDecisionByNameStub = stub
}

func (fake *Storage) FindDecisionByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findDecisionByNameMutex.RLock()
	defer fake.findDecisionByNameMutex.RUnlock()
	argsForCall := fake.findDecisionByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) FindDecisionByNameReturns(result1 *domain.Decision, result2 error) {
	fake.findDecisionByNameMutex.Lock()
	defer fake.findDecisionByNameMutex.Unlock()
	fake.FindDecisionByNameStub = nil
	fake.findDecisionByNameReturns = struct {
		result1 *domain.Decision
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindDecisionByNameReturnsOnCall(i int, result1 *domain.Decision, result2 error) {
	fake.findDecisionByNameMutex.Lock()
	defer fake.findDecisionByNameMutex.Unlock()
	fake.FindDecisionByNameStub = nil
	if fake.findDecisionByNameReturnsOnCall == nil {
		fake.findDecisionByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Decision
			result2 error
		})
	}
	fake.findDecisionByNameReturnsOnCall[i] = struct {
		result1 *domain.Decision
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindGoalByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Goal, error) {
	fake.findGoalByNameMutex.Lock()
	ret, specificReturn := fake.findGoalByNameReturnsOnCall[len(fake.findGoalByNameArgsForCall)]
	fake.findGoalByNameArgsForCall = append(fake.findGoalByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindGoalByNameStub
	fakeReturns := fake.findGoalByNameReturns
	fake.recordInvocation("FindGoalByName", []interface{}{arg1, arg2, arg3})
	fake.findGoalByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) FindGoalByNameCallCount() int {
	fake.findGoalByNameMutex.RLock()
	defer fake.findGoalByNameMutex.RUnlock()
	return len(fake.findGoalByNameArgsForCall)
}

func (fake *Storage) FindGoalByNameCalls(stub func(context.Context, string, string) (*domain.Goal, error)) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = stub
}

func (fake *Storage) FindGoalByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findGoalByNameMutex.RLock()
	defer fake.findGoalByNameMutex.RUnlock()
	argsForCall := fake.findGoalByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) FindGoalByNameReturns(result1 *domain.Goal, result2 error) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = nil
	fake.findGoalByNameReturns = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindGoalByNameReturnsOnCall(i int, result1 *domain.Goal, result2 error) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = nil
	if fake.findGoalByNameReturnsOnCall == nil {
		fake.findGoalByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Goal
			result2 error
		})
	}
	fake.findGoalByNameReturnsOnCall[i] = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindObjectiveByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Objective, error) {
	fake.findObjectiveByNameMutex.Lock()
	ret, specificReturn := fake.findObjectiveByNameReturnsOnCall[len(fake.findObjectiveByNameArgsForCall)]
	fake.findObjectiveByNameArgsForCall = append(fake.findObjectiveByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindObjectiveByNameStub
	fakeReturns := fake.findObjectiveByNameReturns
	fake.recordInvocation("FindObjectiveByName", []interface{}{arg1, arg2, arg3})
	fake.findObjectiveByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) FindObjectiveByNameCallCount() int {
	fake.findObjectiveByNameMutex.RLock()
	defer fake.findObjectiveByNameMutex.RUnlock()
	return len(fake.findObjectiveByNameArgsForCall)
}

func (fake *Storage) FindObjectiveByNameCalls(stub func(context.Context, string, string) (*domain.Objective, error)) {
	fake.findObjectiveByNameMutex.Lock()
	defer fake.findObjectiveByNameMutex.Unlock()
	fake.FindObjectiveByNameStub = stub
}

func (fake *Storage) FindObjectiveByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findObjectiveByNameMutex.RLock()
	defer fake.findObjectiveByNameMutex.RUnlock()
	argsForCall := fake.findObjectiveByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) FindObjectiveByNameReturns(result1 *domain.Objective, result2 error) {
	fake.findObjectiveByNameMutex.Lock()
	defer fake.findObjectiveByNameMutex.Unlock()
	fake.FindObjectiveByNameStub = nil
	fake.findObjectiveByNameReturns = struct {
		result1 *domain.Objective
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindObjectiveByNameReturnsOnCall(i int, result1 *domain.Objective, result2 error) {
	fake.findObjectiveByNameMutex.Lock()
	defer fake.findObjectiveByNameMutex.Unlock()
	fake.FindObjectiveByNameStub = nil
	if fake.findObjectiveByNameReturnsOnCall == nil {
		fake.findObjectiveByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Objective
			result2 error
		})
	}
	fake.findObjectiveByNameReturnsOnCall[i] = struct {
		result1 *domain.Objective
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindTaskByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Task, error) {
	fake.findTaskByNameMutex.Lock()
	ret, specificReturn := fake.findTaskByNameReturnsOnCall[len(fake.findTaskByNameArgsForCall)]
	fake.findTaskByNameArgsForCall = append(fake.findTaskByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindTaskByNameStub
	fakeReturns := fake.findTaskByNameReturns
	fake.recordInvocation("FindTaskByName", []interface{}{arg1, arg2, arg3})
	fake.findTaskByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) FindTaskByNameCallCount() int {
	fake.findTaskByNameMutex.RLock()
	defer fake.findTaskByNameMutex.RUnlock()
	return len(fake.findTaskByNameArgsForCall)
}

func (fake *Storage) FindTaskByNameCalls(stub func(context.Context, string, string) (*domain.Task, error)) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = stub
}

func (fake *Storage) FindTaskByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findTaskByNameMutex.RLock()
	defer fake.findTaskByNameMutex.RUnlock()
	argsForCall := fake.findTaskByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) FindTaskByNameReturns(result1 *domain.Task, result2 error) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = nil
	fake.findTaskByNameReturns = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindTaskByNameReturnsOnCall(i int, result1 *domain.Task, result2 error) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = nil
	if fake.findTaskByNameReturnsOnCall == nil {
		fake.findTaskByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Task
			result2 error
		})
	}
	fake.findTaskByNameReturnsOnCall[i] = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindThemeByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Theme, error) {
	fake.findThemeByNameMutex.Lock()
	ret, specificReturn := fake.findThemeByNameReturnsOnCall[len(fake.findThemeByNameArgsForCall)]
	fake.findThemeByNameArgsForCall = append(fake.findThemeByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindThemeByNameStub
	fakeReturns := fake.findThemeByNameReturns
	fake.recordInvocation("FindThemeByName", []interface{}{arg1, arg2, arg3})
	fake.findThemeByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) FindThemeByNameCallCount() int {
	fake.findThemeByNameMutex.RLock()
	defer fake.findThemeByNameMutex.RUnlock()
	return len(fake.findThemeByNameArgsForCall)
}

func (fake *Storage) FindThemeByNameCalls(stub func(context.Context, string, string) (*domain.Theme, error)) {
	fake.findThemeByNameMutex.Lock()
	defer fake.findThemeByNameMutex.Unlock()
	fake.FindThemeByNameStub = stub
}

func (fake *Storage) FindThemeByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findThemeByNameMutex.RLock()
	defer fake.findThemeByNameMutex.RUnlock()
	argsForCall := fake.findThemeByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) FindThemeByNameReturns(result1 *domain.Theme, result2 error) {
	fake.findThemeByNameMutex.Lock()
	defer fake.findThemeByNameMutex.Unlock()
	fake.FindThemeByNameStub = nil
	fake.findThemeByNameReturns = struct {
		result1 *domain.Theme
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindThemeByNameReturnsOnCall(i int, result1 *domain.Theme, result2 error) {
	fake.findThemeByNameMutex.Lock()
	defer fake.findThemeByNameMutex.Unlock()
	fake.FindThemeByNameStub = nil
	if fake.findThemeByNameReturnsOnCall == nil {
		fake.findThemeByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Theme
			result2 error
		})
	}
	fake.findThemeByNameReturnsOnCall[i] = struct {
		result1 *domain.Theme
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindVisionByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Vision, error) {
	fake.findVisionByNameMutex.Lock()
	ret, specificReturn := fake.findVisionByNameReturnsOnCall[len(fake.findVisionByNameArgsForCall)]
	fake.findVisionByNameArgsForCall = append(fake.findVisionByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindVisionByNameStub
	fakeReturns := fake.findVisionByNameReturns
	fake.recordInvocation("FindVisionByName", []interface{}{arg1, arg2, arg3})
	fake.findVisionByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) FindVisionByNameCallCount() int {
	fake.findVisionByNameMutex.RLock()
	defer fake.findVisionByNameMutex.RUnlock()
	return len(fake.findVisionByNameArgsForCall)
}

func (fake *Storage) FindVisionByNameCalls(stub func(context.Context, string, string) (*domain.Vision, error)) {
	fake.findVisionByNameMutex.Lock()
	defer fake.findVisionByNameMutex.Unlock()
	fake.FindVisionByNameStub = stub
}

func (fake *Storage) FindVisionByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findVisionByNameMutex.RLock()
	defer fake.findVisionByNameMutex.RUnlock()
	argsForCall := fake.findVisionByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) FindVisionByNameReturns(result1 *domain.Vision, result2 error) {
	fake.findVisionByNameMutex.Lock()
	defer fake.findVisionByNameMutex.Unlock()
	fake.FindVisionByNameStub = nil
	fake.findVisionByNameReturns = struct {
		result1 *domain.Vision
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindVisionByNameReturnsOnCall(i int, result1 *domain.Vision, result2 error) {
	fake.findVisionByNameMutex.Lock()
	defer fake.findVisionByNameMutex.Unlock()
	fake.FindVisionByNameStub = nil
	if fake.findVisionByNameReturnsOnCall == nil {
		fake.findVisionByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Vision
			result2 error
		})
	}
	fake.findVisionByNameReturnsOnCall[i] = struct {
		result1 *domain.Vision
		result2 error
	}{result1, result2}
}

func (fake *Storage) ListDecisions(arg1 context.Context, arg2 string) ([]*domain.Decision, error) {
	fake.listDecisionsMutex.Lock()
	ret, specificReturn := fake.listDecisionsReturnsOnCall[len(fake.listDecisionsArgsForCall)]
	fake.listDecisionsArgsForCall = append(fake.listDecisionsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListDecisionsStub
	fakeReturns := fake.listDecisionsReturns
	fake.recordInvocation("ListDecisions", []interface{}{arg1, arg2})
	fake.listDecisionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ListDecisionsCallCount() int {
	fake.listDecisionsMutex.RLock()
	defer fake.listDecisionsMutex.RUnlock()
	return len(fake.listDecisionsArgsForCall)
}

func (fake *Storage) ListDecisionsCalls(stub func(context.Context, string) ([]*domain.Decision, error)) {
	fake.listDecisionsMutex.Lock()
	defer fake.listDecisionsMutex.Unlock()
	fake.ListDecisionsStub = stub
}

func (fake *Storage) ListDecisionsArgsForCall(i int) (context.Context, string) {
	fake.listDecisionsMutex.RLock()
	defer fake.listDecisionsMutex.RUnlock()
	argsForCall := fake.listDecisionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) ListDecisionsReturns(result1 []*domain.Decision, result2 error) {
	fake.listDecisionsMutex.Lock()
	defer fake.listDecisionsMutex.Unlock()
	fake.ListDecisionsStub = nil
	fake.listDecisionsReturns = struct {
		result1 []*domain.Decision
		result2 error
	}{result1, result2}
}

func (fake *Storage) ListDecisionsReturnsOnCall(i int, result1 []*domain.Decision, result2 error) {
	fake.listDecisionsMutex.Lock()
	defer fake.listDecisionsMutex.Unlock()
	fake.ListDecisionsStub = nil
	if fake.listDecisionsReturnsOnCall == nil {
		fake.listDecisionsReturnsOnCall = make(map[int]struct {
			result1 []*domain.Decision
			result2 error
		})
	}
	fake.listDecisionsReturnsOnCall[i] = struct {
		result1 []*domain.Decision
		result2 error
	}{result1, result2}
}

func (fake *Storage) ListPages(arg1 context.Context, arg2 string, arg3 string) ([]*domain.Task, error) {
	fake.listPagesMutex.Lock()
	ret, specificReturn := fake.listPagesReturnsOnCall[len(fake.listPagesArgsForCall)]
	fake.listPagesArgsForCall = append(fake.listPagesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ListPagesStub
	fakeReturns := fake.listPagesReturns
	fake.recordInvocation("ListPages", []interface{}{arg1, arg2, arg3})
	fake.listPagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ListPagesCallCount() int {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	return len(fake.listPagesArgsForCall)
}

func (fake *Storage) ListPagesCalls(stub func(context.Context, string, string) ([]*domain.Task, error)) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = stub
}

func (fake *Storage) ListPagesArgsForCall(i int) (context.Context, string, string) {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	argsForCall := fake.listPagesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ListPagesReturns(result1 []*domain.Task, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	fake.listPagesReturns = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ListPagesReturnsOnCall(i int, result1 []*domain.Task, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	if fake.listPagesReturnsOnCall == nil {
		fake.listPagesReturnsOnCall = make(map[int]struct {
			result1 []*domain.Task
			result2 error
		})
	}
	fake.listPagesReturnsOnCall[i] = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ListTasks(arg1 context.Context, arg2 string) ([]*domain.Task, error) {
	fake.listTasksMutex.Lock()
	ret, specificReturn := fake.listTasksReturnsOnCall[len(fake.listTasksArgsForCall)]
	fake.listTasksArgsForCall = append(fake.listTasksArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListTasksStub
	fakeReturns := fake.listTasksReturns
	fake.recordInvocation("ListTasks", []interface{}{arg1, arg2})
	fake.listTasksMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ListTasksCallCount() int {
	fake.listTasksMutex.RLock()
	defer fake.listTasksMutex.RUnlock()
	return len(fake.listTasksArgsForCall)
}

func (fake *Storage) ListTasksCalls(stub func(context.Context, string) ([]*domain.Task, error)) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = stub
}

func (fake *Storage) ListTasksArgsForCall(i int) (context.Context, string) {
	fake.listTasksMutex.RLock()
	defer fake.listTasksMutex.RUnlock()
	argsForCall := fake.listTasksArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) ListTasksReturns(result1 []*domain.Task, result2 error) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = nil
	fake.listTasksReturns = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ListTasksReturnsOnCall(i int, result1 []*domain.Task, result2 error) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = nil
	if fake.listTasksReturnsOnCall == nil {
		fake.listTasksReturnsOnCall = make(map[int]struct {
			result1 []*domain.Task
			result2 error
		})
	}
	fake.listTasksReturnsOnCall[i] = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadDailyNote(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.readDailyNoteMutex.Lock()
	ret, specificReturn := fake.readDailyNoteReturnsOnCall[len(fake.readDailyNoteArgsForCall)]
	fake.readDailyNoteArgsForCall = append(fake.readDailyNoteArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ReadDailyNoteStub
	fakeReturns := fake.readDailyNoteReturns
	fake.recordInvocation("ReadDailyNote", []interface{}{arg1, arg2, arg3})
	fake.readDailyNoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadDailyNoteCallCount() int {
	fake.readDailyNoteMutex.RLock()
	defer fake.readDailyNoteMutex.RUnlock()
	return len(fake.readDailyNoteArgsForCall)
}

func (fake *Storage) ReadDailyNoteCalls(stub func(context.Context, string, string) (string, error)) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = stub
}

func (fake *Storage) ReadDailyNoteArgsForCall(i int) (context.Context, string, string) {
	fake.readDailyNoteMutex.RLock()
	defer fake.readDailyNoteMutex.RUnlock()
	argsForCall := fake.readDailyNoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadDailyNoteReturns(result1 string, result2 error) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = nil
	fake.readDailyNoteReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadDailyNoteReturnsOnCall(i int, result1 string, result2 error) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = nil
	if fake.readDailyNoteReturnsOnCall == nil {
		fake.readDailyNoteReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.readDailyNoteReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadGoal(arg1 context.Context, arg2 string, arg3 domain.GoalID) (*domain.Goal, error) {
	fake.readGoalMutex.Lock()
	ret, specificReturn := fake.readGoalReturnsOnCall[len(fake.readGoalArgsForCall)]
	fake.readGoalArgsForCall = append(fake.readGoalArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 domain.GoalID
	}{arg1, arg2, arg3})
	stub := fake.ReadGoalStub
	fakeReturns := fake.readGoalReturns
	fake.recordInvocation("ReadGoal", []interface{}{arg1, arg2, arg3})
	fake.readGoalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadGoalCallCount() int {
	fake.readGoalMutex.RLock()
	defer fake.readGoalMutex.RUnlock()
	return len(fake.readGoalArgsForCall)
}

func (fake *Storage) ReadGoalCalls(stub func(context.Context, string, domain.GoalID) (*domain.Goal, error)) {
	fake.readGoalMutex.Lock()
	defer fake.readGoalMutex.Unlock()
	fake.ReadGoalStub = stub
}

func (fake *Storage) ReadGoalArgsForCall(i int) (context.Context, string, domain.GoalID) {
	fake.readGoalMutex.RLock()
	defer fake.readGoalMutex.RUnlock()
	argsForCall := fake.readGoalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadGoalReturns(result1 *domain.Goal, result2 error) {
	fake.readGoalMutex.Lock()
	defer fake.readGoalMutex.Unlock()
	fake.ReadGoalStub = nil
	fake.readGoalReturns = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadGoalReturnsOnCall(i int, result1 *domain.Goal, result2 error) {
	fake.readGoalMutex.Lock()
	defer fake.readGoalMutex.Unlock()
	fake.ReadGoalStub = nil
	if fake.readGoalReturnsOnCall == nil {
		fake.readGoalReturnsOnCall = make(map[int]struct {
			result1 *domain.Goal
			result2 error
		})
	}
	fake.readGoalReturnsOnCall[i] = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadObjective(arg1 context.Context, arg2 string, arg3 domain.ObjectiveID) (*domain.Objective, error) {
	fake.readObjectiveMutex.Lock()
	ret, specificReturn := fake.readObjectiveReturnsOnCall[len(fake.readObjectiveArgsForCall)]
	fake.readObjectiveArgsForCall = append(fake.readObjectiveArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 domain.ObjectiveID
	}{arg1, arg2, arg3})
	stub := fake.ReadObjectiveStub
	fakeReturns := fake.readObjectiveReturns
	fake.recordInvocation("ReadObjective", []interface{}{arg1, arg2, arg3})
	fake.readObjectiveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadObjectiveCallCount() int {
	fake.readObjectiveMutex.RLock()
	defer fake.readObjectiveMutex.RUnlock()
	return len(fake.readObjectiveArgsForCall)
}

func (fake *Storage) ReadObjectiveCalls(stub func(context.Context, string, domain.ObjectiveID) (*domain.Objective, error)) {
	fake.readObjectiveMutex.Lock()
	defer fake.readObjectiveMutex.Unlock()
	fake.ReadObjectiveStub = stub
}

func (fake *Storage) ReadObjectiveArgsForCall(i int) (context.Context, string, domain.ObjectiveID) {
	fake.readObjectiveMutex.RLock()
	defer fake.readObjectiveMutex.RUnlock()
	argsForCall := fake.readObjectiveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadObjectiveReturns(result1 *domain.Objective, result2 error) {
	fake.readObjectiveMutex.Lock()
	defer fake.readObjectiveMutex.Unlock()
	fake.ReadObjectiveStub = nil
	fake.readObjectiveReturns = struct {
		result1 *domain.Objective
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadObjectiveReturnsOnCall(i int, result1 *domain.Objective, result2 error) {
	fake.readObjectiveMutex.Lock()
	defer fake.readObjectiveMutex.Unlock()
	fake.ReadObjectiveStub = nil
	if fake.readObjectiveReturnsOnCall == nil {
		fake.readObjectiveReturnsOnCall = make(map[int]struct {
			result1 *domain.Objective
			result2 error
		})
	}
	fake.readObjectiveReturnsOnCall[i] = struct {
		result1 *domain.Objective
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadTask(arg1 context.Context, arg2 string, arg3 domain.TaskID) (*domain.Task, error) {
	fake.readTaskMutex.Lock()
	ret, specificReturn := fake.readTaskReturnsOnCall[len(fake.readTaskArgsForCall)]
	fake.readTaskArgsForCall = append(fake.readTaskArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 domain.TaskID
	}{arg1, arg2, arg3})
	stub := fake.ReadTaskStub
	fakeReturns := fake.readTaskReturns
	fake.recordInvocation("ReadTask", []interface{}{arg1, arg2, arg3})
	fake.readTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadTaskCallCount() int {
	fake.readTaskMutex.RLock()
	defer fake.readTaskMutex.RUnlock()
	return len(fake.readTaskArgsForCall)
}

func (fake *Storage) ReadTaskCalls(stub func(context.Context, string, domain.TaskID) (*domain.Task, error)) {
	fake.readTaskMutex.Lock()
	defer fake.readTaskMutex.Unlock()
	fake.ReadTaskStub = stub
}

func (fake *Storage) ReadTaskArgsForCall(i int) (context.Context, string, domain.TaskID) {
	fake.readTaskMutex.RLock()
	defer fake.readTaskMutex.RUnlock()
	argsForCall := fake.readTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadTaskReturns(result1 *domain.Task, result2 error) {
	fake.readTaskMutex.Lock()
	defer fake.readTaskMutex.Unlock()
	fake.ReadTaskStub = nil
	fake.readTaskReturns = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadTaskReturnsOnCall(i int, result1 *domain.Task, result2 error) {
	fake.readTaskMutex.Lock()
	defer fake.readTaskMutex.Unlock()
	fake.ReadTaskStub = nil
	if fake.readTaskReturnsOnCall == nil {
		fake.readTaskReturnsOnCall = make(map[int]struct {
			result1 *domain.Task
			result2 error
		})
	}
	fake.readTaskReturnsOnCall[i] = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadTheme(arg1 context.Context, arg2 string, arg3 domain.ThemeID) (*domain.Theme, error) {
	fake.readThemeMutex.Lock()
	ret, specificReturn := fake.readThemeReturnsOnCall[len(fake.readThemeArgsForCall)]
	fake.readThemeArgsForCall = append(fake.readThemeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 domain.ThemeID
	}{arg1, arg2, arg3})
	stub := fake.ReadThemeStub
	fakeReturns := fake.readThemeReturns
	fake.recordInvocation("ReadTheme", []interface{}{arg1, arg2, arg3})
	fake.readThemeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadThemeCallCount() int {
	fake.readThemeMutex.RLock()
	defer fake.readThemeMutex.RUnlock()
	return len(fake.readThemeArgsForCall)
}

func (fake *Storage) ReadThemeCalls(stub func(context.Context, string, domain.ThemeID) (*domain.Theme, error)) {
	fake.readThemeMutex.Lock()
	defer fake.readThemeMutex.Unlock()
	fake.ReadThemeStub = stub
}

func (fake *Storage) ReadThemeArgsForCall(i int) (context.Context, string, domain.ThemeID) {
	fake.readThemeMutex.RLock()
	defer fake.readThemeMutex.RUnlock()
	argsForCall := fake.readThemeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadThemeReturns(result1 *domain.Theme, result2 error) {
	fake.readThemeMutex.Lock()
	defer fake.readThemeMutex.Unlock()
	fake.ReadThemeStub = nil
	fake.readThemeReturns = struct {
		result1 *domain.Theme
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadThemeReturnsOnCall(i int, result1 *domain.Theme, result2 error) {
	fake.readThemeMutex.Lock()
	defer fake.readThemeMutex.Unlock()
	fake.ReadThemeStub = nil
	if fake.readThemeReturnsOnCall == nil {
		fake.readThemeReturnsOnCall = make(map[int]struct {
			result1 *domain.Theme
			result2 error
		})
	}
	fake.readThemeReturnsOnCall[i] = struct {
		result1 *domain.Theme
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadVision(arg1 context.Context, arg2 string, arg3 domain.VisionID) (*domain.Vision, error) {
	fake.readVisionMutex.Lock()
	ret, specificReturn := fake.readVisionReturnsOnCall[len(fake.readVisionArgsForCall)]
	fake.readVisionArgsForCall = append(fake.readVisionArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 domain.VisionID
	}{arg1, arg2, arg3})
	stub := fake.ReadVisionStub
	fakeReturns := fake.readVisionReturns
	fake.recordInvocation("ReadVision", []interface{}{arg1, arg2, arg3})
	fake.readVisionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadVisionCallCount() int {
	fake.readVisionMutex.RLock()
	defer fake.readVisionMutex.RUnlock()
	return len(fake.readVisionArgsForCall)
}

func (fake *Storage) ReadVisionCalls(stub func(context.Context, string, domain.VisionID) (*domain.Vision, error)) {
	fake.readVisionMutex.Lock()
	defer fake.readVisionMutex.Unlock()
	fake.ReadVisionStub = stub
}

func (fake *Storage) ReadVisionArgsForCall(i int) (context.Context, string, domain.VisionID) {
	fake.readVisionMutex.RLock()
	defer fake.readVisionMutex.RUnlock()
	argsForCall := fake.readVisionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadVisionReturns(result1 *domain.Vision, result2 error) {
	fake.readVisionMutex.Lock()
	defer fake.readVisionMutex.Unlock()
	fake.ReadVisionStub = nil
	fake.readVisionReturns = struct {
		result1 *domain.Vision
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadVisionReturnsOnCall(i int, result1 *domain.Vision, result2 error) {
	fake.readVisionMutex.Lock()
	defer fake.readVisionMutex.Unlock()
	fake.ReadVisionStub = nil
	if fake.readVisionReturnsOnCall == nil {
		fake.readVisionReturnsOnCall = make(map[int]struct {
			result1 *domain.Vision
			result2 error
		})
	}
	fake.readVisionReturnsOnCall[i] = struct {
		result1 *domain.Vision
		result2 error
	}{result1, result2}
}

func (fake *Storage) WriteDailyNote(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.writeDailyNoteMutex.Lock()
	ret, specificReturn := fake.writeDailyNoteReturnsOnCall[len(fake.writeDailyNoteArgsForCall)]
	fake.writeDailyNoteArgsForCall = append(fake.writeDailyNoteArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.WriteDailyNoteStub
	fakeReturns := fake.writeDailyNoteReturns
	fake.recordInvocation("WriteDailyNote", []interface{}{arg1, arg2, arg3, arg4})
	fake.writeDailyNoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteDailyNoteCallCount() int {
	fake.writeDailyNoteMutex.RLock()
	defer fake.writeDailyNoteMutex.RUnlock()
	return len(fake.writeDailyNoteArgsForCall)
}

func (fake *Storage) WriteDailyNoteCalls(stub func(context.Context, string, string, string) error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = stub
}

func (fake *Storage) WriteDailyNoteArgsForCall(i int) (context.Context, string, string, string) {
	fake.writeDailyNoteMutex.RLock()
	defer fake.writeDailyNoteMutex.RUnlock()
	argsForCall := fake.writeDailyNoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *Storage) WriteDailyNoteReturns(result1 error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = nil
	fake.writeDailyNoteReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteDailyNoteReturnsOnCall(i int, result1 error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = nil
	if fake.writeDailyNoteReturnsOnCall == nil {
		fake.writeDailyNoteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeDailyNoteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteDecision(arg1 context.Context, arg2 *domain.Decision) error {
	fake.writeDecisionMutex.Lock()
	ret, specificReturn := fake.writeDecisionReturnsOnCall[len(fake.writeDecisionArgsForCall)]
	fake.writeDecisionArgsForCall = append(fake.writeDecisionArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Decision
	}{arg1, arg2})
	stub := fake.WriteDecisionStub
	fakeReturns := fake.writeDecisionReturns
	fake.recordInvocation("WriteDecision", []interface{}{arg1, arg2})
	fake.writeDecisionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteDecisionCallCount() int {
	fake.writeDecisionMutex.RLock()
	defer fake.writeDecisionMutex.RUnlock()
	return len(fake.writeDecisionArgsForCall)
}

func (fake *Storage) WriteDecisionCalls(stub func(context.Context, *domain.Decision) error) {
	fake.writeDecisionMutex.Lock()
	defer fake.writeDecisionMutex.Unlock()
	fake.WriteDecisionStub = stub
}

func (fake *Storage) WriteDecisionArgsForCall(i int) (context.Context, *domain.Decision) {
	fake.writeDecisionMutex.RLock()
	defer fake.writeDecisionMutex.RUnlock()
	argsForCall := fake.writeDecisionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteDecisionReturns(result1 error) {
	fake.writeDecisionMutex.Lock()
	defer fake.writeDecisionMutex.Unlock()
	fake.WriteDecisionStub = nil
	fake.writeDecisionReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteDecisionReturnsOnCall(i int, result1 error) {
	fake.writeDecisionMutex.Lock()
	defer fake.writeDecisionMutex.Unlock()
	fake.WriteDecisionStub = nil
	if fake.writeDecisionReturnsOnCall == nil {
		fake.writeDecisionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeDecisionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteGoal(arg1 context.Context, arg2 *domain.Goal) error {
	fake.writeGoalMutex.Lock()
	ret, specificReturn := fake.writeGoalReturnsOnCall[len(fake.writeGoalArgsForCall)]
	fake.writeGoalArgsForCall = append(fake.writeGoalArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Goal
	}{arg1, arg2})
	stub := fake.WriteGoalStub
	fakeReturns := fake.writeGoalReturns
	fake.recordInvocation("WriteGoal", []interface{}{arg1, arg2})
	fake.writeGoalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteGoalCallCount() int {
	fake.writeGoalMutex.RLock()
	defer fake.writeGoalMutex.RUnlock()
	return len(fake.writeGoalArgsForCall)
}

func (fake *Storage) WriteGoalCalls(stub func(context.Context, *domain.Goal) error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = stub
}

func (fake *Storage) WriteGoalArgsForCall(i int) (context.Context, *domain.Goal) {
	fake.writeGoalMutex.RLock()
	defer fake.writeGoalMutex.RUnlock()
	argsForCall := fake.writeGoalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteGoalReturns(result1 error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = nil
	fake.writeGoalReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteGoalReturnsOnCall(i int, result1 error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = nil
	if fake.writeGoalReturnsOnCall == nil {
		fake.writeGoalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeGoalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteObjective(arg1 context.Context, arg2 *domain.Objective) error {
	fake.writeObjectiveMutex.Lock()
	ret, specificReturn := fake.writeObjectiveReturnsOnCall[len(fake.writeObjectiveArgsForCall)]
	fake.writeObjectiveArgsForCall = append(fake.writeObjectiveArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Objective
	}{arg1, arg2})
	stub := fake.WriteObjectiveStub
	fakeReturns := fake.writeObjectiveReturns
	fake.recordInvocation("WriteObjective", []interface{}{arg1, arg2})
	fake.writeObjectiveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteObjectiveCallCount() int {
	fake.writeObjectiveMutex.RLock()
	defer fake.writeObjectiveMutex.RUnlock()
	return len(fake.writeObjectiveArgsForCall)
}

func (fake *Storage) WriteObjectiveCalls(stub func(context.Context, *domain.Objective) error) {
	fake.writeObjectiveMutex.Lock()
	defer fake.writeObjectiveMutex.Unlock()
	fake.WriteObjectiveStub = stub
}

func (fake *Storage) WriteObjectiveArgsForCall(i int) (context.Context, *domain.Objective) {
	fake.writeObjectiveMutex.RLock()
	defer fake.writeObjectiveMutex.RUnlock()
	argsForCall := fake.writeObjectiveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteObjectiveReturns(result1 error) {
	fake.writeObjectiveMutex.Lock()
	defer fake.writeObjectiveMutex.Unlock()
	fake.WriteObjectiveStub = nil
	fake.writeObjectiveReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteObjectiveReturnsOnCall(i int, result1 error) {
	fake.writeObjectiveMutex.Lock()
	defer fake.writeObjectiveMutex.Unlock()
	fake.WriteObjectiveStub = nil
	if fake.writeObjectiveReturnsOnCall == nil {
		fake.writeObjectiveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeObjectiveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteTask(arg1 context.Context, arg2 *domain.Task) error {
	fake.writeTaskMutex.Lock()
	ret, specificReturn := fake.writeTaskReturnsOnCall[len(fake.writeTaskArgsForCall)]
	fake.writeTaskArgsForCall = append(fake.writeTaskArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Task
	}{arg1, arg2})
	stub := fake.WriteTaskStub
	fakeReturns := fake.writeTaskReturns
	fake.recordInvocation("WriteTask", []interface{}{arg1, arg2})
	fake.writeTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteTaskCallCount() int {
	fake.writeTaskMutex.RLock()
	defer fake.writeTaskMutex.RUnlock()
	return len(fake.writeTaskArgsForCall)
}

func (fake *Storage) WriteTaskCalls(stub func(context.Context, *domain.Task) error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = stub
}

func (fake *Storage) WriteTaskArgsForCall(i int) (context.Context, *domain.Task) {
	fake.writeTaskMutex.RLock()
	defer fake.writeTaskMutex.RUnlock()
	argsForCall := fake.writeTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteTaskReturns(result1 error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = nil
	fake.writeTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteTaskReturnsOnCall(i int, result1 error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = nil
	if fake.writeTaskReturnsOnCall == nil {
		fake.writeTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteTheme(arg1 context.Context, arg2 *domain.Theme) error {
	fake.writeThemeMutex.Lock()
	ret, specificReturn := fake.writeThemeReturnsOnCall[len(fake.writeThemeArgsForCall)]
	fake.writeThemeArgsForCall = append(fake.writeThemeArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Theme
	}{arg1, arg2})
	stub := fake.WriteThemeStub
	fakeReturns := fake.writeThemeReturns
	fake.recordInvocation("WriteTheme", []interface{}{arg1, arg2})
	fake.writeThemeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteThemeCallCount() int {
	fake.writeThemeMutex.RLock()
	defer fake.writeThemeMutex.RUnlock()
	return len(fake.writeThemeArgsForCall)
}

func (fake *Storage) WriteThemeCalls(stub func(context.Context, *domain.Theme) error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = stub
}

func (fake *Storage) WriteThemeArgsForCall(i int) (context.Context, *domain.Theme) {
	fake.writeThemeMutex.RLock()
	defer fake.writeThemeMutex.RUnlock()
	argsForCall := fake.writeThemeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteThemeReturns(result1 error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = nil
	fake.writeThemeReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteThemeReturnsOnCall(i int, result1 error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = nil
	if fake.writeThemeReturnsOnCall == nil {
		fake.writeThemeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeThemeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteVision(arg1 context.Context, arg2 *domain.Vision) error {
	fake.writeVisionMutex.Lock()
	ret, specificReturn := fake.writeVisionReturnsOnCall[len(fake.writeVisionArgsForCall)]
	fake.writeVisionArgsForCall = append(fake.writeVisionArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Vision
	}{arg1, arg2})
	stub := fake.WriteVisionStub
	fakeReturns := fake.writeVisionReturns
	fake.recordInvocation("WriteVision", []interface{}{arg1, arg2})
	fake.writeVisionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteVisionCallCount() int {
	fake.writeVisionMutex.RLock()
	defer fake.writeVisionMutex.RUnlock()
	return len(fake.writeVisionArgsForCall)
}

func (fake *Storage) WriteVisionCalls(stub func(context.Context, *domain.Vision) error) {
	fake.writeVisionMutex.Lock()
	defer fake.writeVisionMutex.Unlock()
	fake.WriteVisionStub = stub
}

func (fake *Storage) WriteVisionArgsForCall(i int) (context.Context, *domain.Vision) {
	fake.writeVisionMutex.RLock()
	defer fake.writeVisionMutex.RUnlock()
	argsForCall := fake.writeVisionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteVisionReturns(result1 error) {
	fake.writeVisionMutex.Lock()
	defer fake.writeVisionMutex.Unlock()
	fake.WriteVisionStub = nil
	fake.writeVisionReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteVisionReturnsOnCall(i int, result1 error) {
	fake.writeVisionMutex.Lock()
	defer fake.writeVisionMutex.Unlock()
	fake.WriteVisionStub = nil
	if fake.writeVisionReturnsOnCall == nil {
		fake.writeVisionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeVisionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Storage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.Storage = new(Storage)
