// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-cli/pkg/storage"
)

type Storage struct {
	FindGoalByNameStub        func(context.Context, string, string) (*domain.Goal, error)
	findGoalByNameMutex       sync.RWMutex
	findGoalByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findGoalByNameReturns struct {
		result1 *domain.Goal
		result2 error
	}
	findGoalByNameReturnsOnCall map[int]struct {
		result1 *domain.Goal
		result2 error
	}
	FindTaskByNameStub        func(context.Context, string, string) (*domain.Task, error)
	findTaskByNameMutex       sync.RWMutex
	findTaskByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findTaskByNameReturns struct {
		result1 *domain.Task
		result2 error
	}
	findTaskByNameReturnsOnCall map[int]struct {
		result1 *domain.Task
		result2 error
	}
	ListTasksStub        func(context.Context, string) ([]*domain.Task, error)
	listTasksMutex       sync.RWMutex
	listTasksArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listTasksReturns struct {
		result1 []*domain.Task
		result2 error
	}
	listTasksReturnsOnCall map[int]struct {
		result1 []*domain.Task
		result2 error
	}
	ReadDailyNoteStub        func(context.Context, string, string) (string, error)
	readDailyNoteMutex       sync.RWMutex
	readDailyNoteArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	readDailyNoteReturns struct {
		result1 string
		result2 error
	}
	readDailyNoteReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ReadGoalStub        func(context.Context, string, domain.GoalID) (*domain.Goal, error)
	readGoalMutex       sync.RWMutex
	readGoalArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 domain.GoalID
	}
	readGoalReturns struct {
		result1 *domain.Goal
		result2 error
	}
	readGoalReturnsOnCall map[int]struct {
		result1 *domain.Goal
		result2 error
	}
	ReadTaskStub        func(context.Context, string, domain.TaskID) (*domain.Task, error)
	readTaskMutex       sync.RWMutex
	readTaskArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 domain.TaskID
	}
	readTaskReturns struct {
		result1 *domain.Task
		result2 error
	}
	readTaskReturnsOnCall map[int]struct {
		result1 *domain.Task
		result2 error
	}
	ReadThemeStub        func(context.Context, string, domain.ThemeID) (*domain.Theme, error)
	readThemeMutex       sync.RWMutex
	readThemeArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 domain.ThemeID
	}
	readThemeReturns struct {
		result1 *domain.Theme
		result2 error
	}
	readThemeReturnsOnCall map[int]struct {
		result1 *domain.Theme
		result2 error
	}
	WriteDailyNoteStub        func(context.Context, string, string, string) error
	writeDailyNoteMutex       sync.RWMutex
	writeDailyNoteArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	writeDailyNoteReturns struct {
		result1 error
	}
	writeDailyNoteReturnsOnCall map[int]struct {
		result1 error
	}
	WriteGoalStub        func(context.Context, *domain.Goal) error
	writeGoalMutex       sync.RWMutex
	writeGoalArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Goal
	}
	writeGoalReturns struct {
		result1 error
	}
	writeGoalReturnsOnCall map[int]struct {
		result1 error
	}
	WriteTaskStub        func(context.Context, *domain.Task) error
	writeTaskMutex       sync.RWMutex
	writeTaskArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Task
	}
	writeTaskReturns struct {
		result1 error
	}
	writeTaskReturnsOnCall map[int]struct {
		result1 error
	}
	WriteThemeStub        func(context.Context, *domain.Theme) error
	writeThemeMutex       sync.RWMutex
	writeThemeArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Theme
	}
	writeThemeReturns struct {
		result1 error
	}
	writeThemeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Storage) FindGoalByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Goal, error) {
	fake.findGoalByNameMutex.Lock()
	ret, specificReturn := fake.findGoalByNameReturnsOnCall[len(fake.findGoalByNameArgsForCall)]
	fake.findGoalByNameArgsForCall = append(fake.findGoalByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindGoalByNameStub
	fakeReturns := fake.findGoalByNameReturns
	fake.recordInvocation("FindGoalByName", []interface{}{arg1, arg2, arg3})
	fake.findGoalByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) FindGoalByNameCallCount() int {
	fake.findGoalByNameMutex.RLock()
	defer fake.findGoalByNameMutex.RUnlock()
	return len(fake.findGoalByNameArgsForCall)
}

func (fake *Storage) FindGoalByNameCalls(stub func(context.Context, string, string) (*domain.Goal, error)) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = stub
}

func (fake *Storage) FindGoalByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findGoalByNameMutex.RLock()
	defer fake.findGoalByNameMutex.RUnlock()
	argsForCall := fake.findGoalByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) FindGoalByNameReturns(result1 *domain.Goal, result2 error) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = nil
	fake.findGoalByNameReturns = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindGoalByNameReturnsOnCall(i int, result1 *domain.Goal, result2 error) {
	fake.findGoalByNameMutex.Lock()
	defer fake.findGoalByNameMutex.Unlock()
	fake.FindGoalByNameStub = nil
	if fake.findGoalByNameReturnsOnCall == nil {
		fake.findGoalByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Goal
			result2 error
		})
	}
	fake.findGoalByNameReturnsOnCall[i] = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindTaskByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Task, error) {
	fake.findTaskByNameMutex.Lock()
	ret, specificReturn := fake.findTaskByNameReturnsOnCall[len(fake.findTaskByNameArgsForCall)]
	fake.findTaskByNameArgsForCall = append(fake.findTaskByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindTaskByNameStub
	fakeReturns := fake.findTaskByNameReturns
	fake.recordInvocation("FindTaskByName", []interface{}{arg1, arg2, arg3})
	fake.findTaskByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) FindTaskByNameCallCount() int {
	fake.findTaskByNameMutex.RLock()
	defer fake.findTaskByNameMutex.RUnlock()
	return len(fake.findTaskByNameArgsForCall)
}

func (fake *Storage) FindTaskByNameCalls(stub func(context.Context, string, string) (*domain.Task, error)) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = stub
}

func (fake *Storage) FindTaskByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findTaskByNameMutex.RLock()
	defer fake.findTaskByNameMutex.RUnlock()
	argsForCall := fake.findTaskByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) FindTaskByNameReturns(result1 *domain.Task, result2 error) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = nil
	fake.findTaskByNameReturns = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) FindTaskByNameReturnsOnCall(i int, result1 *domain.Task, result2 error) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = nil
	if fake.findTaskByNameReturnsOnCall == nil {
		fake.findTaskByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Task
			result2 error
		})
	}
	fake.findTaskByNameReturnsOnCall[i] = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ListTasks(arg1 context.Context, arg2 string) ([]*domain.Task, error) {
	fake.listTasksMutex.Lock()
	ret, specificReturn := fake.listTasksReturnsOnCall[len(fake.listTasksArgsForCall)]
	fake.listTasksArgsForCall = append(fake.listTasksArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListTasksStub
	fakeReturns := fake.listTasksReturns
	fake.recordInvocation("ListTasks", []interface{}{arg1, arg2})
	fake.listTasksMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ListTasksCallCount() int {
	fake.listTasksMutex.RLock()
	defer fake.listTasksMutex.RUnlock()
	return len(fake.listTasksArgsForCall)
}

func (fake *Storage) ListTasksCalls(stub func(context.Context, string) ([]*domain.Task, error)) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = stub
}

func (fake *Storage) ListTasksArgsForCall(i int) (context.Context, string) {
	fake.listTasksMutex.RLock()
	defer fake.listTasksMutex.RUnlock()
	argsForCall := fake.listTasksArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) ListTasksReturns(result1 []*domain.Task, result2 error) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = nil
	fake.listTasksReturns = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ListTasksReturnsOnCall(i int, result1 []*domain.Task, result2 error) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = nil
	if fake.listTasksReturnsOnCall == nil {
		fake.listTasksReturnsOnCall = make(map[int]struct {
			result1 []*domain.Task
			result2 error
		})
	}
	fake.listTasksReturnsOnCall[i] = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadDailyNote(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.readDailyNoteMutex.Lock()
	ret, specificReturn := fake.readDailyNoteReturnsOnCall[len(fake.readDailyNoteArgsForCall)]
	fake.readDailyNoteArgsForCall = append(fake.readDailyNoteArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ReadDailyNoteStub
	fakeReturns := fake.readDailyNoteReturns
	fake.recordInvocation("ReadDailyNote", []interface{}{arg1, arg2, arg3})
	fake.readDailyNoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadDailyNoteCallCount() int {
	fake.readDailyNoteMutex.RLock()
	defer fake.readDailyNoteMutex.RUnlock()
	return len(fake.readDailyNoteArgsForCall)
}

func (fake *Storage) ReadDailyNoteCalls(stub func(context.Context, string, string) (string, error)) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = stub
}

func (fake *Storage) ReadDailyNoteArgsForCall(i int) (context.Context, string, string) {
	fake.readDailyNoteMutex.RLock()
	defer fake.readDailyNoteMutex.RUnlock()
	argsForCall := fake.readDailyNoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadDailyNoteReturns(result1 string, result2 error) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = nil
	fake.readDailyNoteReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadDailyNoteReturnsOnCall(i int, result1 string, result2 error) {
	fake.readDailyNoteMutex.Lock()
	defer fake.readDailyNoteMutex.Unlock()
	fake.ReadDailyNoteStub = nil
	if fake.readDailyNoteReturnsOnCall == nil {
		fake.readDailyNoteReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.readDailyNoteReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadGoal(arg1 context.Context, arg2 string, arg3 domain.GoalID) (*domain.Goal, error) {
	fake.readGoalMutex.Lock()
	ret, specificReturn := fake.readGoalReturnsOnCall[len(fake.readGoalArgsForCall)]
	fake.readGoalArgsForCall = append(fake.readGoalArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 domain.GoalID
	}{arg1, arg2, arg3})
	stub := fake.ReadGoalStub
	fakeReturns := fake.readGoalReturns
	fake.recordInvocation("ReadGoal", []interface{}{arg1, arg2, arg3})
	fake.readGoalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadGoalCallCount() int {
	fake.readGoalMutex.RLock()
	defer fake.readGoalMutex.RUnlock()
	return len(fake.readGoalArgsForCall)
}

func (fake *Storage) ReadGoalCalls(stub func(context.Context, string, domain.GoalID) (*domain.Goal, error)) {
	fake.readGoalMutex.Lock()
	defer fake.readGoalMutex.Unlock()
	fake.ReadGoalStub = stub
}

func (fake *Storage) ReadGoalArgsForCall(i int) (context.Context, string, domain.GoalID) {
	fake.readGoalMutex.RLock()
	defer fake.readGoalMutex.RUnlock()
	argsForCall := fake.readGoalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadGoalReturns(result1 *domain.Goal, result2 error) {
	fake.readGoalMutex.Lock()
	defer fake.readGoalMutex.Unlock()
	fake.ReadGoalStub = nil
	fake.readGoalReturns = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadGoalReturnsOnCall(i int, result1 *domain.Goal, result2 error) {
	fake.readGoalMutex.Lock()
	defer fake.readGoalMutex.Unlock()
	fake.ReadGoalStub = nil
	if fake.readGoalReturnsOnCall == nil {
		fake.readGoalReturnsOnCall = make(map[int]struct {
			result1 *domain.Goal
			result2 error
		})
	}
	fake.readGoalReturnsOnCall[i] = struct {
		result1 *domain.Goal
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadTask(arg1 context.Context, arg2 string, arg3 domain.TaskID) (*domain.Task, error) {
	fake.readTaskMutex.Lock()
	ret, specificReturn := fake.readTaskReturnsOnCall[len(fake.readTaskArgsForCall)]
	fake.readTaskArgsForCall = append(fake.readTaskArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 domain.TaskID
	}{arg1, arg2, arg3})
	stub := fake.ReadTaskStub
	fakeReturns := fake.readTaskReturns
	fake.recordInvocation("ReadTask", []interface{}{arg1, arg2, arg3})
	fake.readTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadTaskCallCount() int {
	fake.readTaskMutex.RLock()
	defer fake.readTaskMutex.RUnlock()
	return len(fake.readTaskArgsForCall)
}

func (fake *Storage) ReadTaskCalls(stub func(context.Context, string, domain.TaskID) (*domain.Task, error)) {
	fake.readTaskMutex.Lock()
	defer fake.readTaskMutex.Unlock()
	fake.ReadTaskStub = stub
}

func (fake *Storage) ReadTaskArgsForCall(i int) (context.Context, string, domain.TaskID) {
	fake.readTaskMutex.RLock()
	defer fake.readTaskMutex.RUnlock()
	argsForCall := fake.readTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadTaskReturns(result1 *domain.Task, result2 error) {
	fake.readTaskMutex.Lock()
	defer fake.readTaskMutex.Unlock()
	fake.ReadTaskStub = nil
	fake.readTaskReturns = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadTaskReturnsOnCall(i int, result1 *domain.Task, result2 error) {
	fake.readTaskMutex.Lock()
	defer fake.readTaskMutex.Unlock()
	fake.ReadTaskStub = nil
	if fake.readTaskReturnsOnCall == nil {
		fake.readTaskReturnsOnCall = make(map[int]struct {
			result1 *domain.Task
			result2 error
		})
	}
	fake.readTaskReturnsOnCall[i] = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadTheme(arg1 context.Context, arg2 string, arg3 domain.ThemeID) (*domain.Theme, error) {
	fake.readThemeMutex.Lock()
	ret, specificReturn := fake.readThemeReturnsOnCall[len(fake.readThemeArgsForCall)]
	fake.readThemeArgsForCall = append(fake.readThemeArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 domain.ThemeID
	}{arg1, arg2, arg3})
	stub := fake.ReadThemeStub
	fakeReturns := fake.readThemeReturns
	fake.recordInvocation("ReadTheme", []interface{}{arg1, arg2, arg3})
	fake.readThemeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Storage) ReadThemeCallCount() int {
	fake.readThemeMutex.RLock()
	defer fake.readThemeMutex.RUnlock()
	return len(fake.readThemeArgsForCall)
}

func (fake *Storage) ReadThemeCalls(stub func(context.Context, string, domain.ThemeID) (*domain.Theme, error)) {
	fake.readThemeMutex.Lock()
	defer fake.readThemeMutex.Unlock()
	fake.ReadThemeStub = stub
}

func (fake *Storage) ReadThemeArgsForCall(i int) (context.Context, string, domain.ThemeID) {
	fake.readThemeMutex.RLock()
	defer fake.readThemeMutex.RUnlock()
	argsForCall := fake.readThemeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Storage) ReadThemeReturns(result1 *domain.Theme, result2 error) {
	fake.readThemeMutex.Lock()
	defer fake.readThemeMutex.Unlock()
	fake.ReadThemeStub = nil
	fake.readThemeReturns = struct {
		result1 *domain.Theme
		result2 error
	}{result1, result2}
}

func (fake *Storage) ReadThemeReturnsOnCall(i int, result1 *domain.Theme, result2 error) {
	fake.readThemeMutex.Lock()
	defer fake.readThemeMutex.Unlock()
	fake.ReadThemeStub = nil
	if fake.readThemeReturnsOnCall == nil {
		fake.readThemeReturnsOnCall = make(map[int]struct {
			result1 *domain.Theme
			result2 error
		})
	}
	fake.readThemeReturnsOnCall[i] = struct {
		result1 *domain.Theme
		result2 error
	}{result1, result2}
}

func (fake *Storage) WriteDailyNote(arg1 context.Context, arg2 string, arg3 string, arg4 string) error {
	fake.writeDailyNoteMutex.Lock()
	ret, specificReturn := fake.writeDailyNoteReturnsOnCall[len(fake.writeDailyNoteArgsForCall)]
	fake.writeDailyNoteArgsForCall = append(fake.writeDailyNoteArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.WriteDailyNoteStub
	fakeReturns := fake.writeDailyNoteReturns
	fake.recordInvocation("WriteDailyNote", []interface{}{arg1, arg2, arg3, arg4})
	fake.writeDailyNoteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteDailyNoteCallCount() int {
	fake.writeDailyNoteMutex.RLock()
	defer fake.writeDailyNoteMutex.RUnlock()
	return len(fake.writeDailyNoteArgsForCall)
}

func (fake *Storage) WriteDailyNoteCalls(stub func(context.Context, string, string, string) error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = stub
}

func (fake *Storage) WriteDailyNoteArgsForCall(i int) (context.Context, string, string, string) {
	fake.writeDailyNoteMutex.RLock()
	defer fake.writeDailyNoteMutex.RUnlock()
	argsForCall := fake.writeDailyNoteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *Storage) WriteDailyNoteReturns(result1 error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = nil
	fake.writeDailyNoteReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteDailyNoteReturnsOnCall(i int, result1 error) {
	fake.writeDailyNoteMutex.Lock()
	defer fake.writeDailyNoteMutex.Unlock()
	fake.WriteDailyNoteStub = nil
	if fake.writeDailyNoteReturnsOnCall == nil {
		fake.writeDailyNoteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeDailyNoteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteGoal(arg1 context.Context, arg2 *domain.Goal) error {
	fake.writeGoalMutex.Lock()
	ret, specificReturn := fake.writeGoalReturnsOnCall[len(fake.writeGoalArgsForCall)]
	fake.writeGoalArgsForCall = append(fake.writeGoalArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Goal
	}{arg1, arg2})
	stub := fake.WriteGoalStub
	fakeReturns := fake.writeGoalReturns
	fake.recordInvocation("WriteGoal", []interface{}{arg1, arg2})
	fake.writeGoalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteGoalCallCount() int {
	fake.writeGoalMutex.RLock()
	defer fake.writeGoalMutex.RUnlock()
	return len(fake.writeGoalArgsForCall)
}

func (fake *Storage) WriteGoalCalls(stub func(context.Context, *domain.Goal) error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = stub
}

func (fake *Storage) WriteGoalArgsForCall(i int) (context.Context, *domain.Goal) {
	fake.writeGoalMutex.RLock()
	defer fake.writeGoalMutex.RUnlock()
	argsForCall := fake.writeGoalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteGoalReturns(result1 error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = nil
	fake.writeGoalReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteGoalReturnsOnCall(i int, result1 error) {
	fake.writeGoalMutex.Lock()
	defer fake.writeGoalMutex.Unlock()
	fake.WriteGoalStub = nil
	if fake.writeGoalReturnsOnCall == nil {
		fake.writeGoalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeGoalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteTask(arg1 context.Context, arg2 *domain.Task) error {
	fake.writeTaskMutex.Lock()
	ret, specificReturn := fake.writeTaskReturnsOnCall[len(fake.writeTaskArgsForCall)]
	fake.writeTaskArgsForCall = append(fake.writeTaskArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Task
	}{arg1, arg2})
	stub := fake.WriteTaskStub
	fakeReturns := fake.writeTaskReturns
	fake.recordInvocation("WriteTask", []interface{}{arg1, arg2})
	fake.writeTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteTaskCallCount() int {
	fake.writeTaskMutex.RLock()
	defer fake.writeTaskMutex.RUnlock()
	return len(fake.writeTaskArgsForCall)
}

func (fake *Storage) WriteTaskCalls(stub func(context.Context, *domain.Task) error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = stub
}

func (fake *Storage) WriteTaskArgsForCall(i int) (context.Context, *domain.Task) {
	fake.writeTaskMutex.RLock()
	defer fake.writeTaskMutex.RUnlock()
	argsForCall := fake.writeTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteTaskReturns(result1 error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = nil
	fake.writeTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteTaskReturnsOnCall(i int, result1 error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = nil
	if fake.writeTaskReturnsOnCall == nil {
		fake.writeTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteTheme(arg1 context.Context, arg2 *domain.Theme) error {
	fake.writeThemeMutex.Lock()
	ret, specificReturn := fake.writeThemeReturnsOnCall[len(fake.writeThemeArgsForCall)]
	fake.writeThemeArgsForCall = append(fake.writeThemeArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Theme
	}{arg1, arg2})
	stub := fake.WriteThemeStub
	fakeReturns := fake.writeThemeReturns
	fake.recordInvocation("WriteTheme", []interface{}{arg1, arg2})
	fake.writeThemeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) WriteThemeCallCount() int {
	fake.writeThemeMutex.RLock()
	defer fake.writeThemeMutex.RUnlock()
	return len(fake.writeThemeArgsForCall)
}

func (fake *Storage) WriteThemeCalls(stub func(context.Context, *domain.Theme) error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = stub
}

func (fake *Storage) WriteThemeArgsForCall(i int) (context.Context, *domain.Theme) {
	fake.writeThemeMutex.RLock()
	defer fake.writeThemeMutex.RUnlock()
	argsForCall := fake.writeThemeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Storage) WriteThemeReturns(result1 error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = nil
	fake.writeThemeReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) WriteThemeReturnsOnCall(i int, result1 error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = nil
	if fake.writeThemeReturnsOnCall == nil {
		fake.writeThemeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeThemeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Storage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.Storage = new(Storage)
