// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-cli/pkg/storage"
)

type TaskStorage struct {
	FindTaskByNameStub        func(context.Context, string, string) (*domain.Task, error)
	findTaskByNameMutex       sync.RWMutex
	findTaskByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findTaskByNameReturns struct {
		result1 *domain.Task
		result2 error
	}
	findTaskByNameReturnsOnCall map[int]struct {
		result1 *domain.Task
		result2 error
	}
	ListTasksStub        func(context.Context, string) ([]*domain.Task, error)
	listTasksMutex       sync.RWMutex
	listTasksArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listTasksReturns struct {
		result1 []*domain.Task
		result2 error
	}
	listTasksReturnsOnCall map[int]struct {
		result1 []*domain.Task
		result2 error
	}
	WriteTaskStub        func(context.Context, *domain.Task) error
	writeTaskMutex       sync.RWMutex
	writeTaskArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Task
	}
	writeTaskReturns struct {
		result1 error
	}
	writeTaskReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TaskStorage) FindTaskByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Task, error) {
	fake.findTaskByNameMutex.Lock()
	ret, specificReturn := fake.findTaskByNameReturnsOnCall[len(fake.findTaskByNameArgsForCall)]
	fake.findTaskByNameArgsForCall = append(fake.findTaskByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindTaskByNameStub
	fakeReturns := fake.findTaskByNameReturns
	fake.recordInvocation("FindTaskByName", []interface{}{arg1, arg2, arg3})
	fake.findTaskByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TaskStorage) FindTaskByNameCallCount() int {
	fake.findTaskByNameMutex.RLock()
	defer fake.findTaskByNameMutex.RUnlock()
	return len(fake.findTaskByNameArgsForCall)
}

func (fake *TaskStorage) FindTaskByNameCalls(stub func(context.Context, string, string) (*domain.Task, error)) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = stub
}

func (fake *TaskStorage) FindTaskByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findTaskByNameMutex.RLock()
	defer fake.findTaskByNameMutex.RUnlock()
	argsForCall := fake.findTaskByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *TaskStorage) FindTaskByNameReturns(result1 *domain.Task, result2 error) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = nil
	fake.findTaskByNameReturns = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *TaskStorage) FindTaskByNameReturnsOnCall(i int, result1 *domain.Task, result2 error) {
	fake.findTaskByNameMutex.Lock()
	defer fake.findTaskByNameMutex.Unlock()
	fake.FindTaskByNameStub = nil
	if fake.findTaskByNameReturnsOnCall == nil {
		fake.findTaskByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Task
			result2 error
		})
	}
	fake.findTaskByNameReturnsOnCall[i] = struct {
		result1 *domain.Task
		result2 error
	}{result1, result2}
}

func (fake *TaskStorage) ListTasks(arg1 context.Context, arg2 string) ([]*domain.Task, error) {
	fake.listTasksMutex.Lock()
	ret, specificReturn := fake.listTasksReturnsOnCall[len(fake.listTasksArgsForCall)]
	fake.listTasksArgsForCall = append(fake.listTasksArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListTasksStub
	fakeReturns := fake.listTasksReturns
	fake.recordInvocation("ListTasks", []interface{}{arg1, arg2})
	fake.listTasksMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TaskStorage) ListTasksCallCount() int {
	fake.listTasksMutex.RLock()
	defer fake.listTasksMutex.RUnlock()
	return len(fake.listTasksArgsForCall)
}

func (fake *TaskStorage) ListTasksCalls(stub func(context.Context, string) ([]*domain.Task, error)) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = stub
}

func (fake *TaskStorage) ListTasksArgsForCall(i int) (context.Context, string) {
	fake.listTasksMutex.RLock()
	defer fake.listTasksMutex.RUnlock()
	argsForCall := fake.listTasksArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TaskStorage) ListTasksReturns(result1 []*domain.Task, result2 error) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = nil
	fake.listTasksReturns = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *TaskStorage) ListTasksReturnsOnCall(i int, result1 []*domain.Task, result2 error) {
	fake.listTasksMutex.Lock()
	defer fake.listTasksMutex.Unlock()
	fake.ListTasksStub = nil
	if fake.listTasksReturnsOnCall == nil {
		fake.listTasksReturnsOnCall = make(map[int]struct {
			result1 []*domain.Task
			result2 error
		})
	}
	fake.listTasksReturnsOnCall[i] = struct {
		result1 []*domain.Task
		result2 error
	}{result1, result2}
}

func (fake *TaskStorage) WriteTask(arg1 context.Context, arg2 *domain.Task) error {
	fake.writeTaskMutex.Lock()
	ret, specificReturn := fake.writeTaskReturnsOnCall[len(fake.writeTaskArgsForCall)]
	fake.writeTaskArgsForCall = append(fake.writeTaskArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Task
	}{arg1, arg2})
	stub := fake.WriteTaskStub
	fakeReturns := fake.writeTaskReturns
	fake.recordInvocation("WriteTask", []interface{}{arg1, arg2})
	fake.writeTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TaskStorage) WriteTaskCallCount() int {
	fake.writeTaskMutex.RLock()
	defer fake.writeTaskMutex.RUnlock()
	return len(fake.writeTaskArgsForCall)
}

func (fake *TaskStorage) WriteTaskCalls(stub func(context.Context, *domain.Task) error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = stub
}

func (fake *TaskStorage) WriteTaskArgsForCall(i int) (context.Context, *domain.Task) {
	fake.writeTaskMutex.RLock()
	defer fake.writeTaskMutex.RUnlock()
	argsForCall := fake.writeTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TaskStorage) WriteTaskReturns(result1 error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = nil
	fake.writeTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *TaskStorage) WriteTaskReturnsOnCall(i int, result1 error) {
	fake.writeTaskMutex.Lock()
	defer fake.writeTaskMutex.Unlock()
	fake.WriteTaskStub = nil
	if fake.writeTaskReturnsOnCall == nil {
		fake.writeTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TaskStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TaskStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.TaskStorage = new(TaskStorage)
