// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-cli/pkg/storage"
)

type ThemeStorage struct {
	FindThemeByNameStub        func(context.Context, string, string) (*domain.Theme, error)
	findThemeByNameMutex       sync.RWMutex
	findThemeByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findThemeByNameReturns struct {
		result1 *domain.Theme
		result2 error
	}
	findThemeByNameReturnsOnCall map[int]struct {
		result1 *domain.Theme
		result2 error
	}
	WriteThemeStub        func(context.Context, *domain.Theme) error
	writeThemeMutex       sync.RWMutex
	writeThemeArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Theme
	}
	writeThemeReturns struct {
		result1 error
	}
	writeThemeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ThemeStorage) FindThemeByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Theme, error) {
	fake.findThemeByNameMutex.Lock()
	ret, specificReturn := fake.findThemeByNameReturnsOnCall[len(fake.findThemeByNameArgsForCall)]
	fake.findThemeByNameArgsForCall = append(fake.findThemeByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindThemeByNameStub
	fakeReturns := fake.findThemeByNameReturns
	fake.recordInvocation("FindThemeByName", []interface{}{arg1, arg2, arg3})
	fake.findThemeByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ThemeStorage) FindThemeByNameCallCount() int {
	fake.findThemeByNameMutex.RLock()
	defer fake.findThemeByNameMutex.RUnlock()
	return len(fake.findThemeByNameArgsForCall)
}

func (fake *ThemeStorage) FindThemeByNameCalls(stub func(context.Context, string, string) (*domain.Theme, error)) {
	fake.findThemeByNameMutex.Lock()
	defer fake.findThemeByNameMutex.Unlock()
	fake.FindThemeByNameStub = stub
}

func (fake *ThemeStorage) FindThemeByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findThemeByNameMutex.RLock()
	defer fake.findThemeByNameMutex.RUnlock()
	argsForCall := fake.findThemeByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ThemeStorage) FindThemeByNameReturns(result1 *domain.Theme, result2 error) {
	fake.findThemeByNameMutex.Lock()
	defer fake.findThemeByNameMutex.Unlock()
	fake.FindThemeByNameStub = nil
	fake.findThemeByNameReturns = struct {
		result1 *domain.Theme
		result2 error
	}{result1, result2}
}

func (fake *ThemeStorage) FindThemeByNameReturnsOnCall(i int, result1 *domain.Theme, result2 error) {
	fake.findThemeByNameMutex.Lock()
	defer fake.findThemeByNameMutex.Unlock()
	fake.FindThemeByNameStub = nil
	if fake.findThemeByNameReturnsOnCall == nil {
		fake.findThemeByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Theme
			result2 error
		})
	}
	fake.findThemeByNameReturnsOnCall[i] = struct {
		result1 *domain.Theme
		result2 error
	}{result1, result2}
}

func (fake *ThemeStorage) WriteTheme(arg1 context.Context, arg2 *domain.Theme) error {
	fake.writeThemeMutex.Lock()
	ret, specificReturn := fake.writeThemeReturnsOnCall[len(fake.writeThemeArgsForCall)]
	fake.writeThemeArgsForCall = append(fake.writeThemeArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Theme
	}{arg1, arg2})
	stub := fake.WriteThemeStub
	fakeReturns := fake.writeThemeReturns
	fake.recordInvocation("WriteTheme", []interface{}{arg1, arg2})
	fake.writeThemeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ThemeStorage) WriteThemeCallCount() int {
	fake.writeThemeMutex.RLock()
	defer fake.writeThemeMutex.RUnlock()
	return len(fake.writeThemeArgsForCall)
}

func (fake *ThemeStorage) WriteThemeCalls(stub func(context.Context, *domain.Theme) error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = stub
}

func (fake *ThemeStorage) WriteThemeArgsForCall(i int) (context.Context, *domain.Theme) {
	fake.writeThemeMutex.RLock()
	defer fake.writeThemeMutex.RUnlock()
	argsForCall := fake.writeThemeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ThemeStorage) WriteThemeReturns(result1 error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = nil
	fake.writeThemeReturns = struct {
		result1 error
	}{result1}
}

func (fake *ThemeStorage) WriteThemeReturnsOnCall(i int, result1 error) {
	fake.writeThemeMutex.Lock()
	defer fake.writeThemeMutex.Unlock()
	fake.WriteThemeStub = nil
	if fake.writeThemeReturnsOnCall == nil {
		fake.writeThemeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeThemeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ThemeStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ThemeStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.ThemeStorage = new(ThemeStorage)
