// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/config"
	"github.com/bborbe/vault-cli/pkg/ops"
)

type VaultDispatcher struct {
	FirstSuccessStub        func(context.Context, []*config.Vault, func(vault *config.Vault) error) error
	firstSuccessMutex       sync.RWMutex
	firstSuccessArgsForCall []struct {
		arg1 context.Context
		arg2 []*config.Vault
		arg3 func(vault *config.Vault) error
	}
	firstSuccessReturns struct {
		result1 error
	}
	firstSuccessReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *VaultDispatcher) FirstSuccess(arg1 context.Context, arg2 []*config.Vault, arg3 func(vault *config.Vault) error) error {
	var arg2Copy []*config.Vault
	if arg2 != nil {
		arg2Copy = make([]*config.Vault, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.firstSuccessMutex.Lock()
	ret, specificReturn := fake.firstSuccessReturnsOnCall[len(fake.firstSuccessArgsForCall)]
	fake.firstSuccessArgsForCall = append(fake.firstSuccessArgsForCall, struct {
		arg1 context.Context
		arg2 []*config.Vault
		arg3 func(vault *config.Vault) error
	}{arg1, arg2Copy, arg3})
	stub := fake.FirstSuccessStub
	fakeReturns := fake.firstSuccessReturns
	fake.recordInvocation("FirstSuccess", []interface{}{arg1, arg2Copy, arg3})
	fake.firstSuccessMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *VaultDispatcher) FirstSuccessCallCount() int {
	fake.firstSuccessMutex.RLock()
	defer fake.firstSuccessMutex.RUnlock()
	return len(fake.firstSuccessArgsForCall)
}

func (fake *VaultDispatcher) FirstSuccessCalls(stub func(context.Context, []*config.Vault, func(vault *config.Vault) error) error) {
	fake.firstSuccessMutex.Lock()
	defer fake.firstSuccessMutex.Unlock()
	fake.FirstSuccessStub = stub
}

func (fake *VaultDispatcher) FirstSuccessArgsForCall(i int) (context.Context, []*config.Vault, func(vault *config.Vault) error) {
	fake.firstSuccessMutex.RLock()
	defer fake.firstSuccessMutex.RUnlock()
	argsForCall := fake.firstSuccessArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *VaultDispatcher) FirstSuccessReturns(result1 error) {
	fake.firstSuccessMutex.Lock()
	defer fake.firstSuccessMutex.Unlock()
	fake.FirstSuccessStub = nil
	fake.firstSuccessReturns = struct {
		result1 error
	}{result1}
}

func (fake *VaultDispatcher) FirstSuccessReturnsOnCall(i int, result1 error) {
	fake.firstSuccessMutex.Lock()
	defer fake.firstSuccessMutex.Unlock()
	fake.FirstSuccessStub = nil
	if fake.firstSuccessReturnsOnCall == nil {
		fake.firstSuccessReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.firstSuccessReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *VaultDispatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *VaultDispatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ops.VaultDispatcher = new(VaultDispatcher)
