// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-cli/pkg/storage"
)

type VisionStorage struct {
	FindVisionByNameStub        func(context.Context, string, string) (*domain.Vision, error)
	findVisionByNameMutex       sync.RWMutex
	findVisionByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	findVisionByNameReturns struct {
		result1 *domain.Vision
		result2 error
	}
	findVisionByNameReturnsOnCall map[int]struct {
		result1 *domain.Vision
		result2 error
	}
	WriteVisionStub        func(context.Context, *domain.Vision) error
	writeVisionMutex       sync.RWMutex
	writeVisionArgsForCall []struct {
		arg1 context.Context
		arg2 *domain.Vision
	}
	writeVisionReturns struct {
		result1 error
	}
	writeVisionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *VisionStorage) FindVisionByName(arg1 context.Context, arg2 string, arg3 string) (*domain.Vision, error) {
	fake.findVisionByNameMutex.Lock()
	ret, specificReturn := fake.findVisionByNameReturnsOnCall[len(fake.findVisionByNameArgsForCall)]
	fake.findVisionByNameArgsForCall = append(fake.findVisionByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.FindVisionByNameStub
	fakeReturns := fake.findVisionByNameReturns
	fake.recordInvocation("FindVisionByName", []interface{}{arg1, arg2, arg3})
	fake.findVisionByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *VisionStorage) FindVisionByNameCallCount() int {
	fake.findVisionByNameMutex.RLock()
	defer fake.findVisionByNameMutex.RUnlock()
	return len(fake.findVisionByNameArgsForCall)
}

func (fake *VisionStorage) FindVisionByNameCalls(stub func(context.Context, string, string) (*domain.Vision, error)) {
	fake.findVisionByNameMutex.Lock()
	defer fake.findVisionByNameMutex.Unlock()
	fake.FindVisionByNameStub = stub
}

func (fake *VisionStorage) FindVisionByNameArgsForCall(i int) (context.Context, string, string) {
	fake.findVisionByNameMutex.RLock()
	defer fake.findVisionByNameMutex.RUnlock()
	argsForCall := fake.findVisionByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *VisionStorage) FindVisionByNameReturns(result1 *domain.Vision, result2 error) {
	fake.findVisionByNameMutex.Lock()
	defer fake.findVisionByNameMutex.Unlock()
	fake.FindVisionByNameStub = nil
	fake.findVisionByNameReturns = struct {
		result1 *domain.Vision
		result2 error
	}{result1, result2}
}

func (fake *VisionStorage) FindVisionByNameReturnsOnCall(i int, result1 *domain.Vision, result2 error) {
	fake.findVisionByNameMutex.Lock()
	defer fake.findVisionByNameMutex.Unlock()
	fake.FindVisionByNameStub = nil
	if fake.findVisionByNameReturnsOnCall == nil {
		fake.findVisionByNameReturnsOnCall = make(map[int]struct {
			result1 *domain.Vision
			result2 error
		})
	}
	fake.findVisionByNameReturnsOnCall[i] = struct {
		result1 *domain.Vision
		result2 error
	}{result1, result2}
}

func (fake *VisionStorage) WriteVision(arg1 context.Context, arg2 *domain.Vision) error {
	fake.writeVisionMutex.Lock()
	ret, specificReturn := fake.writeVisionReturnsOnCall[len(fake.writeVisionArgsForCall)]
	fake.writeVisionArgsForCall = append(fake.writeVisionArgsForCall, struct {
		arg1 context.Context
		arg2 *domain.Vision
	}{arg1, arg2})
	stub := fake.WriteVisionStub
	fakeReturns := fake.writeVisionReturns
	fake.recordInvocation("WriteVision", []interface{}{arg1, arg2})
	fake.writeVisionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *VisionStorage) WriteVisionCallCount() int {
	fake.writeVisionMutex.RLock()
	defer fake.writeVisionMutex.RUnlock()
	return len(fake.writeVisionArgsForCall)
}

func (fake *VisionStorage) WriteVisionCalls(stub func(context.Context, *domain.Vision) error) {
	fake.writeVisionMutex.Lock()
	defer fake.writeVisionMutex.Unlock()
	fake.WriteVisionStub = stub
}

func (fake *VisionStorage) WriteVisionArgsForCall(i int) (context.Context, *domain.Vision) {
	fake.writeVisionMutex.RLock()
	defer fake.writeVisionMutex.RUnlock()
	argsForCall := fake.writeVisionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *VisionStorage) WriteVisionReturns(result1 error) {
	fake.writeVisionMutex.Lock()
	defer fake.writeVisionMutex.Unlock()
	fake.WriteVisionStub = nil
	fake.writeVisionReturns = struct {
		result1 error
	}{result1}
}

func (fake *VisionStorage) WriteVisionReturnsOnCall(i int, result1 error) {
	fake.writeVisionMutex.Lock()
	defer fake.writeVisionMutex.Unlock()
	fake.WriteVisionStub = nil
	if fake.writeVisionReturnsOnCall == nil {
		fake.writeVisionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeVisionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *VisionStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *VisionStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.VisionStorage = new(VisionStorage)
